### ISSUE TITLE
Testing v2.2.0 - beta23

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#165] opened 2023-02-15 23:43 UTC
@cleidigh 
just quick test for now

ptng settings
![grafik](https://user-images.githubusercontent.com/77779094/219217145-38ecacee-d294-4afd-849c-ea0e78a64905.png)

accept/save

reopen settings
![grafik](https://user-images.githubusercontent.com/77779094/219217760-b574a420-cc22-4a13-87db-712bd740d952.png)

please look at the slight differences, but main problem resolved

print preview
![grafik](https://user-images.githubusercontent.com/77779094/219218520-91d78ffb-6635-49ad-974c-453d91b3a431.png)
worked - but some values are mixed of comma and point

about:config() - needed tb restart to see changes
![grafik](https://user-images.githubusercontent.com/77779094/219220140-a91a0691-4328-46a3-9d1d-8bd97e250ab5.png)

well done
good night
@RRoenn

**Comment by cleidigh** [comment] 2023-02-15 23:57
@RRoenn 
Excellent!
I also found preferences not always updated 
I will fix the decimal issues.
Great testing work.
@cleidigh

**Comment by cleidigh** [comment] 2023-02-16 00:00
@tidebre67
@kiki-ja 
Are you able to confirm?
@cleidigh

**Comment by kiki-ja** [comment] 2023-02-16 11:59
@cleidigh 

I have presented the test results below.
https://github.com/cleidigh/printing-tools-ng/issues/139#issuecomment-1432973738

@kiki-ja

**Comment by tidebre67** [comment] 2023-02-16 16:02
@cleidigh 
hi all,
a lot has been written in this respect.I just tested b23
and can report as follows:

Printers concerned:
-save to PDF *
-PDF24
-local HP printer
-Microsoft xps Document Writer
-Microsoft Print to PDF


Print Preview:
margins in mm, *except printer save to PDF
e.g. TOP 14.99  bottom 13.00
     left 24.99  right 24.99
above figures in mm

PTNG settings: margins identical as in Print Preview
*again except printer save to PDF

When changing margins in Print preview same will
be shown in PTNG settings, the other way round same.

Print preview:
page selection works

Print of copies:
1 page message: if selecting 2 or more copies, only 1 copy printed.
More than 1 page per message, printed copies as selected.


paper_size_unit:
in Config editor (about:config):
only the below is in the config editor:
![paper_size](https://user-images.githubusercontent.com/44371934/219419828-60a1688c-70e4-4233-8424-f5985857b3df.png)


Finally:
PTNG settings: Miscellaneous:
Date format: Custom does not work

**Comment by cleidigh** [comment] 2023-02-16 17:54
@tidebre67 
I note 3 issues 
1. Save to PDF units mismatch?
2. # copies printed not consistent 
3. Date custom 

I understand 2 & 3 and will try to reproduce 
Can you be clearer with #1, what is stored in preferences for the margins?
What is shown in preview?
@cleidigh

**Comment by cleidigh** [comment] 2023-02-16 18:02
@RRoenn 
From your testing I summarize : 
- Using the comma decimal only for ptng margins entry in ptng, all margins were saved as inches in preferences and shown correctly in preview 
- An entry in ptng of X.  Results in a bad number save of 0 into margins 

So your results are 100% correct margin handling  (I am placing the decimal as a trivial,known item)
@cleidigh

**Comment by cleidigh** [comment] 2023-02-16 18:06
@kiki-ja 
Your results with margins were all correct.
Copies not working for the MS printer
Since paperSizeUnit is not used at all now, we can ignore it 
@cleidigh

**Comment by cleidigh** [comment] 2023-02-16 18:22
@RRoenn 
@kiki-ja 
@tidebre67 
The issue with decimal use:

- There is quite a mix of use uncorrelated to metric use
- preview allows both, but shows invalid for X.  
- I will follow preview allow both,disable OK for X.

@cleidigh

**Comment by cleidigh** [comment] 2023-02-16 18:32
@tidebre67 
Can you describe the issue with the custom date, I cannot see a problem.
@cleidigh

**Comment by tidebre67** [comment] 2023-02-16 18:47
> @tidebre67 Can you describe the issue with the custom date, I cannot see a problem. @cleidigh

@cleidigh 
pls look at the fllwg:
![ptng settings](https://user-images.githubusercontent.com/44371934/219458091-577df6e1-d417-4d87-b7f9-6ffa2c83de3b.png)
![msg](https://user-images.githubusercontent.com/44371934/219458113-cbbeae6c-23e1-4135-8219-e3ec6d3e381f.png)
![config editor](https://user-images.githubusercontent.com/44371934/219458456-aa0d4217-fa39-4536-9644-7a2367de2ca3.png)

there is no change in short, long, custom, etc and looks always as above.

**Comment by cleidigh** [comment] 2023-02-16 19:00
ok great I will add some debug to determine why the format is not used

**Comment by tidebre67** [comment] 2023-02-16 19:16
> @tidebre67 I note 3 issues
> 
> 1. Save to PDF units mismatch?
> 2. # copies printed not consistent
> 3. Date custom
> 
> I understand 2 & 3 and will try to reproduce Can you be clearer with #1, what is stored in preferences for the margins? What is shown in preview? @cleidigh

@cleidigh 

#1:
set figures as fllws:
![ptng settings before](https://user-images.githubusercontent.com/44371934/219464157-adeb47f4-f3f2-4c91-9f79-68d32ea295e7.png)

after closing and restart of TB:
![ptng settings](https://user-images.githubusercontent.com/44371934/219464367-1308219a-0b20-4d93-bd85-0a0cb0769ce6.png)

print preview figures always unchanged:
![print preview](https://user-images.githubusercontent.com/44371934/219463973-4780a98f-b094-42b9-ae09-7f221c617a51.png)

config editor looks always 
![config before](https://user-images.githubusercontent.com/44371934/219464626-cbe53c0e-9118-4061-938c-23a120a0aa03.png)

**Comment by cleidigh** [comment] 2023-02-16 21:02
@tidebre67 
The config editor margins you show are for the Microsoft not the Mozilla pdf printer which is what you show in ptng 
@cleidigh

**Comment by RRoenn** [comment] 2023-02-16 21:51
@cleidigh @tidebre67 

> Print of copies:
> 1 page message: if selecting 2 or more copies, only 1 copy printed.
> More than 1 page per message, printed copies as selected.

I can confirm this bug. But I can't trace any correlation between 1-page or multi-page messages. It occurs on all attempts.
**Steps to reproduce**
1. set all printers to 3 copies in ptng setting (other settings are irrelevant)
2. go to print preview - selected a non pdf printer
3. first printer has set 3 copies
4. **change to different non pdf printer**
5. copies are set to 1
6. go thru all non pdf printer
7. every printer expect the first is now set to 1 copy
8. **go to ptng setting my initial setting with 3 copies is also  changed to 1**

(only print preview changed, no real print)

@RRoenn

**Comment by RRoenn** [comment] 2023-02-16 21:58
@cleidigh 
> Since paperSizeUnit is not used at all now, we can ignore it

I thought the paper_size_unit is used to display mm or inches. That's why I was very surprised that this entry has disappeared @tidebre67  ...
How do you distinguish the units now?

I still have all paper_size_unit entries

@RRoenn

**Comment by cleidigh** [comment] 2023-02-16 22:03
@RRoenn 
I don't understand the correlation either.
One thing about above. Changing printers in preview will charge copies to Default 1, ptng cannot change it.

I am wondering if the timing is part of this problem. I am concerned this cannot be fixed. We may have to remove it. Fortunately it is the least likely thing to be used.

I want the margins solid, but I don't get the unexplained Mozilla pdf issue @tidebre67 reports.
@cleidigh

**Comment by RRoenn** [comment] 2023-02-16 22:05
@cleidigh 

> 3\. Date custom

I can't confirm this bug with my setting
I used the default custom date string you provided

![grafik](https://user-images.githubusercontent.com/77779094/219497263-75fa28d7-9c32-488f-baff-87b55fba2f84.png)

@RRoenn

**Comment by RRoenn** [comment] 2023-02-16 22:14
@cleidigh 
two last things.
1. If I set 15,5 mm or 15.5 mm it is set to 14.49. Is it possible to get more precise?
2. in the following picture, if I click at the text, the checkbox is selected. Something like this I thought for pages "all" or "custom"
  Ah, now I see, text click is possible but not the deactivated edit field.
  ![grafik](https://user-images.githubusercontent.com/77779094/219498548-f14dae50-68d0-4ca1-b1cd-1780d91cd808.png)

@RRoenn

**Comment by cleidigh** [comment] 2023-02-16 22:14
@RRoenn 
That matches my results. Any date format works. Tested both en and de locales.
@cleidigh

**Comment by RRoenn** [comment] 2023-02-16 22:20
> Changing printers in preview will charge copies to Default 1, ptng cannot change it.

But why changes the print preview some my ptng settings for copy count? Or do you read from tb config?

**Comment by RRoenn** [comment] 2023-02-16 22:27
@cleidigh 

two of my printer don't save the copy counter ...
https://user-images.githubusercontent.com/77779094/219501194-cf1073ff-1a59-4aa2-9644-45c9fcaf7c7a.mp4

**Comment by RRoenn** [comment] 2023-02-16 22:39
back again with wrench ...

![grafik](https://user-images.githubusercontent.com/77779094/219503041-6093cc19-bf25-4872-812b-4f53b0d5d269.png)

**Comment by cleidigh** [comment] 2023-02-16 22:48
@RRoenn 
The lack of wrench is a startup issue have not resolved.

The copies are not stored in printer settings. In preview we overwrite after dialog opens. This does not seem reliable.

**Comment by cleidigh** [comment] 2023-02-16 22:51
@RRoenn 
I think I resolved all the decimal issues.
@cleidigh

**Comment by cleidigh** [comment] 2023-02-16 23:15
@tidebre67 
@RRoenn 
@kiki-ja 
New probable bug:
I have just seen the paper type in preview blank.  I am assuming a missing paperId in preferences. This may be related to @tidebre67 issue.
Have to reproduce. 
@cleidigh

**Comment by RRoenn** [comment] 2023-02-16 23:16
@cleidigh 
> The copies are not stored in printer settings. In preview we overwrite after dialog opens. This does not seem reliable.

I think, the question is, why are the copy setting for the two printer is not stored in the ptng settings config (see picture). They are set to 1, without print preview.
@RRoenn

**Comment by cleidigh** [comment] 2023-02-16 23:56
@RRoenn 
I cannot see an image for copies...

I have looking at the rounding. It looks bad and will always be seen with in to mm conversion. Have to see if I can figure out what preview does.
@cleidigh

**Comment by RRoenn** [comment] 2023-02-17 06:26
> @RRoenn I cannot see an image for copies...

@cleidigh 
I mean this image. All copies where set to 3 in ptng settings. Not all have 3 in ptng config.
![grafik](https://user-images.githubusercontent.com/77779094/219503041-6093cc19-bf25-4872-812b-4f53b0d5d269.png)

**Comment by tidebre67** [comment] 2023-02-17 07:57
> > @tidebre67 The config editor margins you show are for the Microsoft not the Mozilla pdf printer which is what you show in ptng It looks like they are being set to defaults, this still seems different than others. @cleidigh @cleidigh
> 
> @cleidigh Oh, sorry, picked the wrong one. Will send correct one tomorrow.

@cleidigh 
here now the correct one
![mozilla](https://user-images.githubusercontent.com/44371934/219585152-53081d0d-d401-40b1-80a8-441554a72ebb.png)

**Comment by tidebre67** [comment] 2023-02-17 08:55
@cleidigh 
@RRoenn 

you can ignorre this issue
![issue](https://user-images.githubusercontent.com/44371934/219598137-d4da046b-de2f-461a-b321-228598879b79.png)
as solved by myself as in the config editor
![Screenshot 2023-02-17 094820](https://user-images.githubusercontent.com/44371934/219598379-60d7c5f2-7776-4a4d-aa54-99580166c207.png)
for whatever reason the value was on false.
After change to true correct date format is displayed.

**Comment by kiki-ja** [comment] 2023-02-17 10:27
@cleidigh

>@RRoenn
>@kiki-ja
>@tidebre67
>The issue with decimal use:
>
>    There is quite a mix of use uncorrelated to metric use
>    preview allows both, but shows invalid for X.
>    I will follow preview allow both,disable OK for X.

I understand.

@kiki-ja

**Comment by kiki-ja** [comment] 2023-02-17 10:30
@cleidigh

>@tidebre67
>@RRoenn
>@kiki-ja
>New probable bug:
>I have just seen the paper type in preview blank. I am assuming a missing paperId in preferences. This may be related to @tidebre67 issue.
>Have to reproduce.

Thunderbird 102.8.0 64bit
Windows 10 Pro 22H2 64bit

My case:
- None of the paper types were blank in the print preview. All are displayed.
- On the other hand, there was a mix of printers with 'print_paper_id' blank and those with the specified printer.

![print_paper_id](https://user-images.githubusercontent.com/80428201/219619648-fded4257-c58e-478a-960a-9fca2bf728a5.png)

@kiki-ja

**Comment by kiki-ja** [comment] 2023-02-17 10:32
@cleidigh

Thunderbird 102.8.0 64bit
Windows 10 Pro 22H2 64bit

My case:
- I have not problem with custom data not being reflected.
  e.g. extensions.printingtoolsng.process.date = true(default)
- I have not problem with the wrench icons not displaying.

@kiki-ja

**Comment by cleidigh** [comment] 2023-02-17 17:46
@tidebre67 
@kiki-ja 
@RRoenn 

Current summary for b23 by reporter: 

All
- Issues with Copies not being stored in ptng, some stored as default  1
- Issues with preview not showing copies correctly 
- Issues with printed copies != copies shown in preview 

@cleidigh 
@kiki-ja 
- missing paper Id in some printer preferences 

@tidebre67 
- Date issue - resolved - NON ISSUE 

@tidebre67 
- Mozilla  Save to pdf issue 
- Sorry I still don't understand the issue clearly, will comment below

@cleidigh , All
- period not handled correctly in margin inputs, comma display 
- Fixed in b24
- Conversion of units results in noticeable rounding errors 

@kiki-ja 
- Microsoft publisher printer not respecting copies

C

**Comment by cleidigh** [comment] 2023-02-17 17:53
@tidebre67 
For the save to pdf issue I think I see preview showing default values.
The margins are stored as inches and look fine
So can you describe the sequence and what you you looked at when?
Right now I think this is the only outstanding margin issue 
@cleidigh 
@cleidigh

**Comment by tidebre67** [comment] 2023-02-17 20:20
@cleidigh 
For the save to pdf issue I think I see preview showing default values (12.7).

**YES, IF print.printer_Mozilla_Save_to_PDF.print_paper_size_unit    1
margins in print preview custom mm.
When i change the default values in the print preview e.g to 30 then
the ptng settings show default values. When i close the seetings and go
back to print preview the values are back to default.**

**IF print.printer_Mozilla_Save_to_PDF.print_paper_size_unit     0
Margins in print preview custom inch
Changes of values: print preview inch >> pntg settings mm,
ptng settings mm >> print preview inch

All the margins are stored as inches and look fine (in Config), 
YES irrespective whether print_paper_size_unit reads 0 or 1  !!**

Hope above assists.

**Comment by cleidigh** [comment] 2023-02-17 21:11
@tidebre67 
ok I think my feeble mind gets it.
The preview is showing the units as mm when actually its accepting inches, overflowing on large numbers and setting to defaults.
This is totally unexplainable.

The only thing to do now I think is the following : 
- uninstall b23
- go to preview, change printer to any other than Save to pdf, print to save changes 
- delete all the Mozilla Save to PDF preferences 
- back to preview, change to Save to pdf, print 
- record preferences for printer, should be clean defaults 
- do some changes in preview, print, check 
- see that pdf printer is behaving 
- Now install ptng 24
- Now repeat testing with ptng and preview 

@cleidigh

**Comment by tidebre67** [comment] 2023-02-17 22:10
@cleidigh
checking tomorrow and will come back as soon as possible.

**Comment by tidebre67** [comment] 2023-02-18 11:35
@cleidigh 
unfortunately no success with this instruction.
All works with paper_size_unit value 0 (inch)
i.e. saved inch values in ptng settings are the same as in print preview , the other way round values are saved too.

If i switch to paper_size_unit 1 (mm)
all values switches back to default (ptng settings and print preview)

Although values NOT saved either in ptng settings or in print preview the values are transferred into config editor, always in inches.

For me it looks like an issue with the paper_size_unit, but i'm no expert.

**Comment by tidebre67** [comment] 2023-02-18 13:02
@RRoenn 
can you look how it works/looks on your pc with printer "Als PDF speichern" pls..

**Comment by cleidigh** [comment] 2023-02-18 19:15
@tidebre67 
When you deleted the pdf printer did doing a preview and print bring back the defaults?
Was the units set to 0 which you said works?
@cleidigh

**Comment by tidebre67** [comment] 2023-02-18 20:01
@cleidigh
for both question: yes

regret shorts commt, working from mobile currently.

**Closed** 2023-03-15 00:25 UTC
