### ISSUE TITLE
[bug] margin settings are not kept in print preview

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#162] opened 2023-02-08 21:41 UTC
@cleidigh , seems that the settings e.g. as below are not kept in print preview.
![Settings](https://user-images.githubusercontent.com/44371934/217588818-ffce39a3-99e0-4607-b7e9-a849bb302a41.png)
![margins](https://user-images.githubusercontent.com/44371934/217590682-82baf5a2-7b75-4915-a216-d93ac71b6155.png)

once a print is finished the marked margin jumps back e.g to 12.7 . 
I found that in destinations PDF, local printer apparently not affected. 
No idea whether this was already reported.

_Originally posted by @tidebre67 in https://github.com/cleidigh/printing-tools-ng/issues/159#issuecomment-1422912190_

**Comment by RRoenn** [comment] 2023-02-08 21:46
But with PDF24 I get the same error, it is a pity.
Also with Mozilla_Save_to_PDF, the margins from settings are ignored.

and the next mysterium.
I set margins to 50 - go to print preview - go back to PTNG config - my 50 was changed to 1270.00 - and more and more
this just happen with pdf24

**Comment by tidebre67** [comment] 2023-02-09 17:01
@cleidigh  ,
@RRoenn  ,

i am a bit confused due to lot of latetest comments/questions.
No idea where we currently stand.
Recall latest questions:

printers concerned:
save to PDF, PDF24, local HPColor Laser, Microsoft Print to PDF.

ptng settings:
in local HPColor Laser, Microsoft Print to PDF some strange
figures which not set by me, changed by system.
save to PDF, PDF24 figures stable


config: headers, footers and margins are same as in ptng settings.

Print preview only shows default margins.

**Comment by cleidigh** [comment] 2023-02-09 17:45
@tidebre67 
Yes we have a bunch of things all at once. Let me ask some clarification of above.
You mentioned strange items being set in ptng options, but were not specific, can you give detail? Is this different than the margins?
Were you able to do a console capture going to options change a margin, save then look at the config, see if printer margins match ptng printer pref. Then preview and after check preferences again. That should tell us when it changes. Post output.

I am still trying to reproduce.
@cleidigh

**Comment by cleidigh** [comment] 2023-02-09 18:05
@RRoenn 
I think the 50 turning to 1270 may be a clue. I am wondering if this is related to the units. I continue with the battle tat I cannot reproduce a non us environment no matter what I do.

One wild guess is that through wrong unit gyrations we give the preview margins that are out of range and the preview resets to defaults.
I have to figure out some specific, controlled tests. This is the top priority.
@cleidigh

**Comment by tidebre67** [comment] 2023-02-09 19:24
> @tidebre67 Yes we have a bunch of things all at once. Let me ask some clarification of above. You mentioned strange items being set in ptng options, but were not specific, can you give detail? Is this different than the margins? Were you able to do a console capture going to options change a margin, save then look at the config, see if printer margins match ptng printer pref. Then preview and after check preferences again. That should tell us when it changes. Post output.
> 
> I am still trying to reproduce. @cleidigh

@cleidigh 
as far as the strange figures are concerned pls see here:
![Screenshot 2023-02-09 193809](https://user-images.githubusercontent.com/44371934/217909383-3048d130-cffc-446f-a20e-67fe74a4c5e3.png)

the print preview shows 12.7. (default).
changed the margins in the settings again to default (12.7 mm) except left to 22.7) ,closed the settings with ok,
open again the settings and now this:
![Screenshot 2023-02-09 195903](https://user-images.githubusercontent.com/44371934/217912542-26862e5f-5026-42b5-ae70-f4f3855a08da.png)

Config: pls as follows, margin left :
![config](https://user-images.githubusercontent.com/44371934/217915658-e7e93d3d-9d9e-459a-9d12-e0f36088bc85.png)

but here is something different:
![config 2](https://user-images.githubusercontent.com/44371934/217915765-a91ef78f-c801-47e4-897a-ba6e82768556.png)

Hope you can work with the above.

**Comment by RRoenn** [comment] 2023-02-09 19:28
PTNG b19
Win11

today I have also with my second paper printer (LaserJet E-Mail) the above magins problem.
...
while I writing, the problem is now with all my printers
and if I set 50 or 50.00 after okay, they are set to 50,01 (mm)

**Comment by tidebre67** [comment] 2023-02-09 19:30
@cleidigh 
@RRoenn 
see no problems with header and footer.

**Comment by RRoenn** [comment] 2023-02-09 19:40
I set all
- **print_paper_size_unit** to 1 again
- **print.printer_XXX.print_margin_xxx** to 1

Now I have a totally mess ... where are the PTNG values are stored?

**Comment by cleidigh** [comment] 2023-02-09 19:47
@tidebre67 
Your test is close but we need some intermediate info. Specifically looking at the prefs after your first change before you go back to ptng and capture the console.
@cleidigh

**Comment by RRoenn** [comment] 2023-02-09 19:59
@cleidigh
There is a problem in Thunderbird itself.
all **print_paper_size_unit** are set to 0 - all **print_margin_xxx* are set to 1 or 0.5
no addon installed
if I switch in print preview some printers
the most have in-units but some have mm-units although **print_paper_size_unit** is set to 0 (in)

see my above comments

**Comment by cleidigh** [comment] 2023-02-09 20:02
@RRoenn 
Arrg, I feel like it's going haywire.
Why did you have to set units to 1? I thought that was ok?

The ptng settings are in the ptng pref for each printer. When the settings are saved in the ui the margins and hdrs/ftrs are also saved to the printer prefs.
The preview then reads the printer prefs. 
Something is getting crossed with units, but since I cannot reproduce it's very hard for me to debug.

I think I have to make a specific test for people so we can control the process.
@cleidigh

**Comment by RRoenn** [comment] 2023-02-09 20:05
> Why did you have to set units to 1? I thought that was ok?

no worry, that's just because I tested yesterday an older beta.
Now I will stick to 0 till we get margins to work. Or should I use 1?

**Comment by RRoenn** [comment] 2023-02-09 20:10
I have 7 printers installed
all **print_paper_size_unit** is set to 0

- print_to_pdf, 
- pdf24, 
- and my second lokal printer (same driver) 
have inch.

- the local printers have mm

I am confused. How can I help?

**Comment by tidebre67** [comment] 2023-02-09 20:10
> @tidebre67 Your test is close but we need some intermediate info. Specifically looking at the prefs after your first change before you go back to ptng and capture the console. @cleidigh

@cleidigh 
@RRoenn 
Christopher, just to be clear, you refer to the prefs.js in the profile ?

**Comment by cleidigh** [comment] 2023-02-09 20:33
@RRoenn 
I think we are all very confused ...
Yes that would probably be 2 inches having rounding from conversion at some point.
All
while we can change the units I think this confuses things because the units are tied to the paper type and if these are in conflict I have no idea what happens.
@cleidigh

**Comment by RRoenn** [comment] 2023-02-09 20:42
@cleidigh 
maybe you can work with these hints?

![grafik](https://user-images.githubusercontent.com/77779094/217934517-ca3211b7-5399-40c7-8dbd-bef45e3b9ae6.png)

**Comment by tidebre67** [comment] 2023-02-09 20:43
@cleidigh 
Yes, i am meanwhile totally confused as well. 
I remember from previous info that the print_paper_size_unit of all printers should be set to 1.
I did it , is that still corrrect ?

**Comment by RRoenn** [comment] 2023-02-09 20:47
@tidebre67 
yes, if set to 1 all printer margins are in mm displayed.
But the problem is, internally tb calculates with inch. But some printer with mm and some with inch, see my above picture

**Comment by cleidigh** [comment] 2023-02-09 20:48
@tidebre67 
I mean the prefs viewed in the config editor.
I want to catch an incorrect change to the margins for the current printer.
I just need the time to write a specific list of test steps, but I won't be able to add debug today.

The units are set by paper id, usually 1 based on region, but @RRoenn is showing some id=in when should be mm
@cleidigh

**Comment by RRoenn** [comment] 2023-02-09 20:50
I'll try to set them all to the same values. Lets see what happens

**Comment by cleidigh** [comment] 2023-02-09 20:55
@RRoenn 
Your list is definitely odd because there are several cases where the units do not match the height and width are stored in mm.
I wonder if the units are messed up?
@cleidigh

**Comment by cleidigh** [comment] 2023-02-09 20:58
FYI
I will be offline for about an hour in a few.
You guys will probably be closing for the night so I will keep testing.
@cleidigh

**Comment by RRoenn** [comment] 2023-02-09 21:05
@cleidigh 
now every printer is fine with mm, expect **printer_Mozilla_Save_to_PDF** although **print_paper_size_unit** is set to 0
I set every height to 297 and every width to 210. 
**printer_Mozilla_Save_to_PDF** was automatically set back to 11.6929...

Maybe you can compare againt these value if mm or in paper size ?

paper_id: 504 is A3W (420x297mm)

**Comment by tidebre67** [comment] 2023-02-09 21:11
@RRoenn 
i am closing now, as all this infos are driving me mad now. so i take a nap and mostlikely my brain is restored tomorrow.
Kuddelmuddel is really the correct wording in this respect.

**Comment by RRoenn** [comment] 2023-02-09 21:20
@cleidigh 
now every is looking fine in A4/mm without addon

![grafik](https://user-images.githubusercontent.com/77779094/217941646-4dc18b3f-e110-417a-ae92-263afe8199dd.png)

**Comment by RRoenn** [comment] 2023-02-09 21:35
@cleidigh 

- if paper_size_unit 0 -> width and height similar or equal to letter or A4 in inch => use inch
- if paper_size_unit 1 -> width and height similar or equal to letter or A4 in mm => use mm

Or is that too short-sighted?

**Comment by cleidigh** [comment] 2023-02-10 02:22
@RRoenn 
@tidebre67 
@kiki-ja 
I think I found the issue!
I could not fix yet
Do not waste time testing b19 or b20
can't write more having eye  issues.
@cleidigh

**Comment by RRoenn** [comment] 2023-02-10 05:56
@cleidigh 
take a rest and relax your eyes. Maybe you can open a issue ticket, to get your eyes relaxed and fix that issue ;-)

I could also imagine that the mm/in problems only arose from testing the beta versions.

Be careful in a new profile is the value **paper_size_* ** not yet included in the about:config

@RRoenn

**Comment by cleidigh** [comment] 2023-02-10 14:25
@RRoenn 
I am still looking for an eye debug ;-)
I think you are right the mismatched units and paper types were probably the prior id overwrite.

I found that there was one conversion done wrong. And like you mention no initial prefs until at least one print.
I have to also address that.

hopefully I can get something out today.
@cleidigh

**Comment by cleidigh** [comment] 2023-02-10 21:11
@RRoenn 
yes that should be correct, however, I don't think we can change the units.
Then there are internal conflicts.
@cleidigh

**Comment by cleidigh** [comment] 2023-02-10 22:04
@RRoenn 
@tidebre67 
@kiki-ja 
I think I have a fix, but as you know I can't test your environment.

First we need to start with a good preference set. We will use the Mozilla pdf printer so we can all test the most common setup.

Steps:
- Install b21
- restart tb
- disable ptng
- erase the ptng pref for the Mozilla pdf printer 
  extensions.printingtoolsng.printer.Mozilla_Save_to_PDF
- print an email triggering preview 
- select Save to pdf printer 
- change margins to Default not custom 
- change the current paper type to a different type
- print to pdf saving file, delete file
- you are now back to tb mail view
- start another print
- in preview select a4 paper, print,save, delete again 
- back in tb inspect prefs for Mozilla pdf printer 
- you should see paper is A4
- units should be 1
- paper width and height should be correct in mm
- margins should be 12.7 mm units 
- now we are normal
- enable ptng 
- go and change a margin 
- close with ok
- now inspect margins in both the ptng pref and the Mozilla pdf printer margins prefs, they should match and be in mm
- now try a print, margins should be good 

crossing fingers!!
@cleidigh

**Comment by RRoenn** [comment] 2023-02-10 23:47
@cleidigh 
I tried your cookbook

* Install b21 - done
* restart tb - 102.7.2 (64-Bit) - done
* disable ptng - done
* erase the ptng pref for the Mozilla pdf printer - about:config(): **extensions.printingtoolsng.printer.Mozilla_Save_to_PDF** - done
* print an email triggering preview - open print preview - done
* select Save to pdf printer - done
  1. change margins to Default not custom - done
  2. change the current paper type to a different type - Letter was selected - changed to Legal - done
  3. print to pdf saving file, delete file - done
* you are now back to tb mail view - done
* start another print - done
  1. in preview select a4 paper, print, save, delete again - done
* back in tb inspect prefs for Mozilla pdf printer
  1. you should see paper is A4 - about:config(): **print.printer_Mozilla_Save_to_PDF.print_paper_id** iso_a4 - okay
  2. units should be 1 - about:config(): **print.printer_Mozilla_Save_to_PDF.print_paper_size_unit** - **_NOT okay_**
  3. paper width and height should be correct in mm - about:config(): **print.printer_Mozilla_Save_to_PDF.print_paper_width** and **print.printer_Mozilla_Save_to_PDF.print_paper_height** - **_NOT okay_**
  4. margins should be 12.7 mm units - about:config(): **print.printer_Mozilla_Save_to_PDF.print_margin_** - **_NOT okay_**
* **_additionally_**: about:config(): **print.printer_Mozilla_Save_to_PDF** - deleted all entries
* repeat print preview - select a4 paper, print, save, delete again - check again -  **_NOT okay_** unit is set to 0
* I set about:config(): **print.printer_Mozilla_Save_to_PDF.print_paper_size_unit** to 1 - print preview stays with inch

---

* **now I go on with inch**
* papersize: iso_a4, margins: default not custom (not set in about:config() )
* enable ptng - done - need to restart tb
* go and change a margin - changed from 0.5 to 1.5 - done (no , accepted)
  close with ok
* now inspect margins in both the ptng pref and the Mozilla pdf printer margins prefs, they should match and be in ~mm~ inch
  1. about:config(): **extensions.printingtoolsng.printer.Mozilla_Save_to_PDF** - okay
  2. about:config(): **print.printer_Mozilla_Save_to_PDF.print_paper_** - not set yet
* now try a print, margins should be good - set to 1,5 inch - okay

---

* **now I go on with mm**
  1. erase the ptng pref for the Mozilla pdf printer - about:config(): **extensions.printingtoolsng.printer.Mozilla_Save_to_PDF**
  2. about:config(): **print.printer_Mozilla_Save_to_PDF.print_paper_size_unit** set to 1
  3. about:config(): **print.printer_Mozilla_Save_to_PDF.print_paper_id** isa_a4
  4. about:config(): **print.printer_Mozilla_Save_to_PDF.print_paper_width** set to 210
  5. about:config(): **print.printer_Mozilla_Save_to_PDF.print_paper_height** set to 297
* ptng settings: margins now 1,5 mm
* print preview: margins are 38,1 mm (1,5 in)

If you set margins to default and not custom they are not set in about:config() **print.printer_Mozilla_Save_to_PDF.print_paper_**

I will do a clean and fresh restart with mm.

**Comment by RRoenn** [comment] 2023-02-11 00:08
**restart with mm**

* erase the ptng pref for the Mozilla pdf printer - about:config(): **extensions.printingtoolsng.printer.Mozilla_Save_to_PDF**
* about:config(): **print.printer_Mozilla_Save_to_PDF** - deleted all entries
* about:config(): **print.printer_Mozilla_Save_to_PDF.print_paper_size_unit** set to 1
* about:config(): **print.printer_Mozilla_Save_to_PDF.print_paper_id** set to isa_a4
* about:config(): **print.printer_Mozilla_Save_to_PDF.print_paper_width** set to 210
* about:config(): **print.printer_Mozilla_Save_to_PDF.print_paper_height** set to 297
* about:config(): **print.printer_Mozilla_Save_to_PDF.print_margin_** leave empty
* PTNG settings displayed: margins 0,5 mm
* print preview: 12,7 mm
* PTNG settings: margins changed to 25 mm - close with ok
* about:config(): **print.printer_Mozilla_Save_to_PDF** margin 25
* PTNG settings: margins 25.00
* about:config(): **extensions.printingtoolsng.printer.Mozilla_Save_to_PDF**
 {"numCopies":1,"pageRanges":[],"marginTop":25,"marginBottom":25,"marginLeft":25,"marginRight":25,"headerStrLeft":"","headerStrCenter":"&T","headerStrRight":"","footerStrLeft":"&PT","footerStrCenter":"","footerStrRight":"&D"}

**print preview: 12,7 mm** !!

**Comment by RRoenn** [comment] 2023-02-11 00:24
Interesting, if I set margin in print preview to 40,00 (mm)

print.printer_Mozilla_Save_to_PDF: 1.57500004768372 (unit 1)

if I set print.printer_Mozilla_Save_to_PDF to 20 print preview displayed 12,7 (mm) default, because of the wrong size.

This printer saves all margin in in, unit is used for representation. Please try this.
Maybe your margins are ignored and so set to 12,7 mm?

Good night

**Comment by cleidigh** [comment] 2023-02-11 01:13
@RRoenn 
I am going to try to analyze your results 
I think this may be confusing all of us, I thought Mozilla used mm
this may be another edge condition 
Good night 
@cleidigh

**Comment by RRoenn** [comment] 2023-02-11 09:37
@cleidigh 
Hello again,
I tried with another fresh laptop - only margins in print preview changed and checked in about:config() - and can confirm

**print.printer_Mozilla_Save_to_PDF** - unit 0
- papersize (A4, A3, legal, letter, tabloid)  are set in inch
- margins are set in inch

**print.printer_Microsoft_Print_to_PDF** - unit 1
- papersize (A4, A3, legal, letter, tabloid) are set in mm
- margins are set in inch

**print.printer_HP_Color_LaserJet_M254dw** - unit 0
- papersize (A4, A3, legal, letter, tabloid) are set in mm
- margins are set in inch

**Comment by RRoenn** [comment] 2023-02-11 10:13
next point
I think it is not nessesary to write the values from PTNG settings in about:config() printer settings.

Problem, if I set margins in PTNG settings -> propagated to printer settings -> print preview is with these values.
Changed values in print preview -> propagated to printer settings ...
next time I open print preview - the values from printer settings are used and not restored from PTNG settings (but maybe this is just for beta testing?) - that's also why I asked for fixed scaling option.

So don't change any about:config() printer settings - if PTNG is deactivated or removed, original values are used.
Maybe you also save the corresponding unit in PTNG settings?


Sorry for my long postings

**Comment by cleidigh** [comment] 2023-02-11 15:17
@RRoenn 
@kiki-ja 
@tidebre67 
Above is basically correct. The idea was ptng settings drive the printer settings. If one does not change margins in preview I thik b21 will work if a clean start except I have to separate units from presentation as you observed. 

Maybe setting margins in ptng is not really useful.
The oter settings serve a use that cannot be done inpreview or require extra steps (page range and headers and footers) what advantage is there to setting margins in ptng??

I hate to give up, but I feel it's a burden to you guys when I can't test here.
I was unsuccessful again yesterday to get my windows to be configured for a metric region. My paper units are always inches.
The code documentation is also not consistent.
I think I need your guys input.
@cleidigh 
offline for three hours

**Comment by RRoenn** [comment] 2023-02-14 19:35
@cleidigh 
sorry, needed some time to translate and thinking.

> Above is basically correct. The idea was ptng settings drive the printer settings. If one does not change margins in preview I thik b21 will work if a clean start except I have to separate units from presentation as you observed.

I am with you

> Maybe setting margins in ptng is not really useful. The other settings serve a use that cannot be done inpreview or require extra steps (page range and headers and footers) what advantage is there to setting margins in ptng??

Yes, I thought about that too, since this feature is now implemented twice. And additional maintenance may also be required in the future. I believe function is included in a feature request to be able to fix the margins. For example, the settings in PTNG are fixed in our company. The setting in the print preview can then be adjusted for a print, but the PTNG settings will be used again for the next print. Very good!
This is also the reason why I asked about fixing the scaling.

> I hate to give up, but I feel it's a burden to you guys when I can't test here.

Don't worry, give us a beta and what you want us to test too - and I'll try to be brief too. I don't think anyone got through the long version anymore.

@RRoenn
I hope you understand my comments, even with the google translations.

**Comment by cleidigh** [comment] 2023-02-15 21:42
@RRoenn 
If margins are stored as inches then our prior rev tests must have masked this.
I will try to do b23 with this approach once again I cannot reproduce.
@cleidigh

**Comment by RRoenn** [comment] 2023-02-15 21:47
@cleidigh 
that would be really nice
that's also why I did the tests step by step, hope it helps

@RRoenn

**Comment by cleidigh** [comment] 2023-02-15 23:22
@RRoenn 
That is good, thanks.
b23 now stores in inches and uses locale for presentation.
I made no other charges.
Crossing fingers.
@cleidigh

**Closed** 2023-03-15 00:26 UTC
