### ISSUE TITLE
Integrate  PTNG with FiltaQuila  for automatic printing 

### ISSUE THREAD

**Issue by cleidigh** [cleidigh/printing-tools-ng#94] opened 2022-02-14 00:48 UTC
Work with  @realraven to have messaging between FQ and PTNG
enabling automatic printing 

@cleidigh

**Comment by RealRaven2000** [comment] 2022-02-17 19:59
Some patch code - WIP!

[printing_tools_patch_fq.zip](https://github.com/cleidigh/printing-tools-ng/files/8091807/printing_tools_patch_fq.zip)

**Comment by cleidigh** [comment] 2022-02-22 00:58
i posted a first test
i get multiple handle events on the exp side

**Comment by RealRaven2000** [comment] 2022-02-22 16:17
could you commit your changes?

**Comment by RealRaven2000** [comment] 2022-02-22 23:03
here are the latest changes from todays zoom conference

[content-new.zip](https://github.com/cleidigh/printing-tools-ng/files/8120713/content-new.zip)

**Comment by cleidigh** [comment] 2022-02-24 00:00
@RealRaven2000 
@madvinegar 
@querixg 
@ditchfinder 

All Axel and I have made a formal integration between FiltaQuila and PTNG

first you need the beta fq
https://github.com/cleidigh/printing-tools-ng/files/8091829/filtaquilla-3.3.1pre22.zip

on then enable ptng print in fq actions
create your filter with the print action 
the message will print silently automatically 

please post here with issues 

thanks 
@RealRaven2000 
@cleidigh 


All

**Comment by ditchfinder** [comment] 2022-02-24 10:50
@RealRaven2000
@madvinegar
@querixg
@ditchfinder
@kiki-ja

Windows 10 
FQ 3.3.1pre22 (installed zip file)
PTNG 2.0.7-b14p1 (Installed .xpi)
TB 91.6.1 

Unable to get this to work still I'm afraid.

Used PTNG option ticked in FQ
Set up a new filter in case that was affecting anything.
Filter completes and logs show print action

CTRL + P uses PTNG options correctly

Tried a OS reboot and reinstall of add-ons but no change. 

Only weird thing to note was that after reboot of OS both add-ons ahad already been removed from TB but not by me manually. Is there a setting in TB which automatically does this?

Cheers
Martin

**Comment by RealRaven2000** [comment] 2022-02-24 13:17
> Unable to get this to work still I'm afraid.
> 
> Used PTNG option ticked in FQ Set up a new filter in case that was affecting anything. Filter completes and logs show print action

When we successfully tested on my machine the other day I was definitely using 3.3.1 pre 22 - so it should be ok from that said. Did you install by dragging into extension manager or via "Debug ADd-ons"? The later would explain why they were removed on restart. Just drag the xpi / zip file into Extension manager and it should work. I believe @cleidigh added some logs to JavaScript error console, so you could check what's added there during filtering (Ctrl+Shift+J to open it)

**Comment by ditchfinder** [comment] 2022-02-24 13:23
I Installed by clicking on the cog in the Add-ons manager and "Install Add-on from File"

I'll try again using the drag and drop approach and then look at the JS debugger

**Comment by kiki-ja** [comment] 2022-02-24 13:45
@cleidigh
@RealRaven2000
@madvinegar
@querixg
@ditchfinder
All

FiltaQuilla Filter 3.3.1pre22
PrintingTools NG 2.0.7-**b14** (not -b14p1)
Thunderbird 91.6.1 64bit
Windows 10 Pro 21H2 64bit

The following is a report on the results of the automatic printing.
The result is that only one of the seven messages was printed.
I think it's probably the same as @ditchfinder.

Steps to Reproduce
1. Set "Use PrintingTools NG for printing" as Filter Action in FiltaQuilla.
2. In Filter Rules, set the Match Condition to Subject = "会議" and Action to Print.
3. Manually Run was executed on the target folder.
4. Only one of the seven messages whose subject matched "会議" was printed automatically.
5. The Filter Log shows the record of the automatic printing of the seven messages.

Please refer to the screenshot below.

![自動印刷の結果レポート 2 0 7-b14](https://user-images.githubusercontent.com/80428201/155535598-e91597a2-d6dc-4144-aafe-adec3d8e90c6.png)

@kiki-ja

**Comment by ditchfinder** [comment] 2022-02-24 13:47
OK no change so using the debugger I can see:
Object { command: "printMessage", messageHeader: {…} }
[background.js:159:10](moz-extension://40498e54-0b9a-439d-a9d9-db86e12be14e/background.js)
but no output to printer

Other things to note.
Inorder for 'Print to be an option in Filters I have to tick both the Print and PTNG boxes in FQ

![image](https://user-images.githubusercontent.com/100227960/155536034-5ce3171e-6705-434f-a770-b29f15865478.png)

**Comment by RealRaven2000** [comment] 2022-02-24 14:00
> OK no change so using the debugger I can see: Object { command: "printMessage", messageHeader: {…} } background.js:159:10 but no output to printer
> 
> Other things to note. Inorder for 'Print to be an option in Filters I have to tick both the Print and PTNG boxes in FQ

Yes that's by design. About duplication: The problem is that Thunderbird has a hard time removing actions  (unless you restart Thunderbird). And then it will only work if you have the [x] Print options switched on (this makes the Print command visible as action). the other checkbox "use Printing tools NG for printing" is just an additional option. To make that more obvious I should probably disable the option if the [x] Print option is disabled. 

Since Tb messes up the removal of old actions, the topmost menu items may still trigger old code, so its probably best to restart Tb after installing a new version of FiltaQuilla.

**Comment by ditchfinder** [comment] 2022-02-24 14:12
OK so changed opions in FQ
![image](https://user-images.githubusercontent.com/100227960/155539949-154dc137-c517-4a88-8000-a17edfa60c05.png)
but no option in Filters 
![image](https://user-images.githubusercontent.com/100227960/155540044-2b561744-4d27-49bb-a216-c1b518a8c696.png)

This is after fresh install of FQ, New Filter created with different name and OS restart

**Comment by ditchfinder** [comment] 2022-02-24 14:18
Doh, just reread your post @RealRaven2000, so both print options ticked and then TB restart and duplication is no longer there.
Filter still not working though

**Comment by ditchfinder** [comment] 2022-02-24 14:20
@RealRaven2000 @cleidigh so now another issue. If I right-click on message and try to print using PTNG option I get following errors.
![image](https://user-images.githubusercontent.com/100227960/155541675-d16603c1-2f91-416f-841d-fa8112658524.png)

**Comment by RealRaven2000** [comment] 2022-02-24 14:25
Did you try running the filter manually? that's the best test.

Highlight an email making sure the condition will apply, then select tools / run filters on message (or  use the appropriate quickFilters button, if you have my Add-on quickFilters installed.)
![image](https://user-images.githubusercontent.com/6314674/155542602-98c1195d-594a-4c0a-bd0b-03c9dc03e5af.png)
or 
![image](https://user-images.githubusercontent.com/6314674/155542601-c3d6908f-18a3-4be4-a221-911b8bd2f02d.png)

**Comment by ditchfinder** [comment] 2022-02-24 14:28
Run filter on message reults in this:
![image](https://user-images.githubusercontent.com/100227960/155543049-e9608e16-5cec-40bf-93c6-de63bc1ea7f8.png)

If I right-click on message and use PTNG option it prints but is not hiding the headers which I have set it to in PTNG

**Comment by ditchfinder** [comment] 2022-02-24 16:18
@RealRaven2000 @cleidigh @kiki-ja 

We have a winner !
Installing the p1.zip got it working. Not sure why the .xpi I installed didn't but there you go

**Comment by RealRaven2000** [comment] 2022-02-24 16:22
I am not sure, but maybe @cleidigh didn't commit all the changes I sent him? Just a hunch.

Also I think he should add some safety in his function function handleMessage(message, sender) 
at least he should check whether the passed in message object has:

```
message.command == "printMessage"
```

**Comment by cleidigh** [comment] 2022-02-24 17:03
@RealRaven2000 
@ditchfinder

my changes were a slight modification given other cases needed 
now i will address necessary protections

a quick look may show  incomplete messaging 

i have to reproduce

**Comment by cleidigh** [comment] 2022-02-24 17:09
@ditchfinder
with b14 are all messages printed correctly now?

**Comment by ditchfinder** [comment] 2022-02-24 17:19
@cleidigh  Using the p1.zip posted by @RealRaven2000 above and the FQ 3.3.31 pre22 both installed by drag and drop - messages appear to be auto printing successfully and use the correct PTNG parameters that I set. I can do further testing tomorrow, so far I've only done simple .txt emails.

When I used the "printing-tools-ng-2.0.7-b14p1-tb.xpi" install I couldn't get it to work either auto printing or hiding headers when manually printing once FQ was installed

**Comment by cleidigh** [comment] 2022-02-24 17:29
unfortunately b14p1 was never meant to be used it was between @realraven 
and I

**Comment by cleidigh** [comment] 2022-02-24 17:32
@kiki-ja 
I understand you still have a multiple message issue 
I suspect it's a q issue 
@cleidigh

**Comment by ditchfinder** [comment] 2022-02-24 17:32
Aha - Operator Error strikes again - 
![image](https://user-images.githubusercontent.com/100227960/155576782-6c66555d-a47f-4fe3-8fe9-d43c1407ee7c.png)

If I'd read your post properly from yesterday I might not have wasted everyone's time - sorry about that

**Comment by cleidigh** [comment] 2022-02-24 17:58
All
I see q errors with a run filter on folder it is the darn new engine that has no completion events 


@cleidigh

**Comment by cleidigh** [comment] 2022-02-24 18:10
@ditchfinder 
no problem lots of moving parts 

there is an issue with multiple messages I can see it now
@cleidigh

**Comment by cleidigh** [comment] 2022-02-25 01:15
@RealRaven2000 
i think this will require some form of queing
i also may see duplicate msgs from you but i can't be sure yet

**Comment by kiki-ja** [comment] 2022-02-25 06:23
>@RealRaven2000
>Could it be that you're using the wrong version of PTNG?
>    PrintingTools NG 2.0.7-b14 (not -b14p1)
>try this one:
>p1.zip

Yes, I tried using it.

FiltaQuilla Filter 3.3.1pre22
PrintingTools NG 2.0.7-b14p1 (p1.zip)
Thunderbird 91.6.1 64bit
Windows 10 Pro 21H2 64bit

The following is a report on the results of the automatic printing.
The result was that of the **seven messages** that matched, nothing was printed.

Steps to Reproduce
1. Set "Use PrintingTools NG for printing" as Filter Action in FiltaQuilla.
2. In Filter Rules, set the Match Condition to Subject = "会議" and Action to Print.
3. Manually Run was executed on the target folder.
4. None of the **seven messages** whose **subject matched** "会議" were printed automatically.
5. The Filter Log shows the record of the automatic printing of the seven messages.

Is my procedure wrong?
@RealRaven2000, Are you having success with automatic printing of **multiple messages**?

>@cleidigh
>I understand you still have a multiple message issue
>I suspect it's a q issue

Understood.
I can email you the Thunderbird error console log if you need it.
I hope to have this resolved in the near future.

@kiki-ja

**Comment by kiki-ja** [comment] 2022-02-25 06:46
@3LaHoonK

Are you saying that you want to be able to autoprint with PrintingTools NG alone, without using FiltaQuilla?
In other words, do you want to do autoprinting with message filters and PrintingTools NG?

Which of the following?
1. FiltaQuilla + Message Filter + PrintingTools NG = Auto Print
2. Message Filter + PrintingTools NG = Auto Print
3. Other?

@kiki-ja

**Comment by 3LaHoonK** [comment] 2022-02-25 13:55
> @3LaHoonK
> 
> Are you saying that you want to be able to autoprint with PrintingTools NG alone, without using FiltaQuilla?
> In other words, do you want to do autoprinting with message filters and PrintingTools NG?
> 
> Which of the following?
> 1. FiltaQuilla + Message Filter + PrintingTools NG = Auto Print
> 2. Message Filter + PrintingTools NG = Auto Print
> 3. Other?
> 
> @kiki-ja 



Hello,,

@kiki-ja

The best option is number  2

**Comment by RealRaven2000** [comment] 2022-02-25 17:06
> > @3LaHoonK
> > 1. FiltaQuilla + Message Filter + PrintingTools NG = Auto Print
> > 2. Message Filter + PrintingTools NG = Auto Print
> > 3. Other?
> > 
> > @kiki-ja
> 
> Hello,,
> 
> @kiki-ja
> 
> The best option is number 2

"best"? 

I  (maintainer of FiltaQuilla, since Kent James retired for health reasons) wouldn't say (2) is impossible but you add an awful lot of unneeded complexity to PrintingTools NG - now that we already have integrated PTNG into the core business of FiltaQuilla (augmentation of filter capabilities) it seems highly unnecessary. 

You have to keep in mind that if the highly specialized architecture of Filters changes, I have to adjust the FQ code accordingly based on the technical debt of both the inflexible Thunderbird Core code and the way the Add-on was implemented. I had to spend more than 3 full weeks to convert the code to make it compatible to Tb78 - after Mozilla removed xml bindings, and we are still very very far away from turning it from a mx with experimental APIs (Which requires full system access) into a pure mail extension that's based on the official APIs.

So in my opinion (1) is the best option for keeping the functionality alive. The other advantage of this solution is that this modular approach now also opens the road for integration  of PrintingTools NG into other Add-ons - for instance cardbook or calendar Add-ons. Function bloat is one of the reasons that make software unmanageable. The other advantage is that Christopher will have an easier time converting PTNG to a pure mail extension, and that will translate into more users being able to use and promoting the Add-on. 

What are your thoughts on this, @cleidigh ?

**Comment by cleidigh** [comment] 2022-02-25 19:23
@RealRaven2000 
@3LaHoonK 
Yes, ptng is a header formater at its core, attempting to implement filtering 
would be an enormous effort duplicating all of Axels hard work.

Right now  just getting the  new print engine working reliably is proving very difficult.
@cleidigh

**Comment by cleidigh** [comment] 2022-02-25 19:31
@RealRaven2000 
i Think your side is fine, I was fooled by two emails with the same subject.

the problem is clearly a reentrancy issue.
i am working on a q setup today.
the print system does not like reentrancy as well

**Comment by cleidigh** [comment] 2022-02-26 23:35
@RealRaven2000 
@kiki-ja 
@ditchfinder 
@3LaHoonK 

I think I have a solution to address the reentrancy issue with multiple incoming messages.
Due to my limitations I could not do major testing,but I think I proved the q is mainly working,hopefully we can tease out any issues because I really want to release soon.

Use b15 
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.7/xpi/printing-tools-ng-2.0.7-b15-tb.xpi

@cleidigh

**Comment by 3LaHoonK** [comment] 2022-02-27 07:18
Hello 
@cleidigh 

thunderbird Version 91.6.1 + PrintingTools NG Version 2.0.7-b15 + FiltaQuilla Version 3.3

It works fine but there is a problem

The header of the page cannot be hidden

Awaiting your reply, thank you

![image](https://user-images.githubusercontent.com/30515994/155872565-76715a85-d4dd-4dfd-9e7e-a0bfd9d443c5.png)

![image](https://user-images.githubusercontent.com/30515994/155872602-22e84ed5-2569-45f8-b8bc-b8c0a4554835.png)

**Comment by cleidigh** [comment] 2022-02-27 20:03
@3LaHoonK 
You are using the wrong FiltaQuila, you have to use Axel's beta which has the new PTNG capability.
https://github.com/cleidigh/printing-tools-ng/files/8140168/filtaquilla-3.4pre50.zip

Also look up thread for the image on setting the FiltaQuila action for printing to ptng

Note : 
if you see the grey background with the last line darker, that is tb print not ptng
@cleidigh

**Comment by RealRaven2000** [comment] 2022-02-27 21:07
@3LaHoonK make sure you add a comment or like on my github so you are notified of the latest versions.
https://github.com/RealRaven2000/FiltaQuilla/issues/152#issuecomment-1050708632

**Comment by ditchfinder** [comment] 2022-02-28 10:07
@RealRaven2000 @cleidigh @3LaHoonK @kiki-ja
Windows 10
TB 91.6.1 (32-bit)
FQ 3.3.1pre22
PTNG 2.0.7-b15

2 emails matching filter printed OK without headers as specified in PTNG using Tools > Run messages on folder
Also worked on receipt of email matching filter rules.

Any other testing you need me to do.

(Never noticed my TB was the 32 bit version before - any reason to upgrade to 64?)

**Comment by kiki-ja** [comment] 2022-03-01 15:40
@cleidigh
All

FiltaQuilla 3.3.1pre22
PrintingTools NG 2.0.7-b15
Thunderbird 91.6.1 64bit
Windows 10 Pro 21H2 64bit

Successfully printed 7 messages matched by the message filter in automatic sequence.
It's great. Thank you very much.

@kiki-ja

**Comment by cleidigh** [comment] 2022-03-01 17:16
@3LaHoonK 
With the correct versions were you successful?
@cleidigh

**Comment by 3LaHoonK** [comment] 2022-03-01 19:34
Hello,


@cleidigh


Yes I succeeded thank you and I wish to develop my best thank you

**Comment by cleidigh** [comment] 2022-03-01 19:57
@3LaHoonK 
Excellent! I think that makes us 5/5
I will consider this ready for the release 
Thanks for your help!
@cleidigh

**Comment by RealRaven2000** [comment] 2022-03-02 14:46
> @RealRaven2000 Looks like our cool new integration is testing well! 
> I will be releasing soon, what is your timeline? What shall we tell users? 

I have another new integration feature (this time it integrates filter actions with SmartTemplates, see [issue 153](https://github.com/RealRaven2000/FiltaQuilla/issues/153) - just documented on the "SmartTemplates Premium" support page:

https://smarttemplates.quickfolders.org/premium.html#filterForward

- which I want to release concurrently with the new version of FiltaQuilla very soon (within the next fortnight). PrintingTools NG will be supported from the same version onward - FiltaQuilla 3.4. Since you add significant features are you planning to raise your minor version as well (to 2.1) ?

**Closed** 2022-03-25 16:34 UTC
