### ISSUE TITLE
2.0.6 Beta Test Report

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#72] opened 2021-05-19 16:56 UTC
The following message is not displayed.
Where does this show up?

PrintingTools NG: 2.0.6 b2
OS: Windows 10 Pro 64bit 20H2
Thunderbird: 78.10.2 64bit ja version

[printingtoolsng.properties]
allowFonts=The system option:\n  Allow messages to use other fonts\nhas been enabled
disallowFonts=The system option:\n  Allow messages to use other fonts\nhas been disabled

**Comment by cleidigh** [comment] 2021-05-19 17:52
@kiki-ja 
this is the alert every time the option just toggled for using custom font
![image](https://user-images.githubusercontent.com/25272315/118860471-6f3a2f00-b8a9-11eb-978d-9b100e25f3a9.png)

**Comment by kiki-ja** [comment] 2021-05-19 21:50
@cleidigh 

Thanks for the screenshot.

I found out why the notifications were not showing up.

It was because I did not know that the enable/disable checkbox for specifying the font was a toggle switch.
*The blue area in the screenshot.

I thought the notifications were displayed by selecting the font type, not there.
*The red area in the screenshot.

My wish was not fulfilled, but I understand.

**Font Toggle Notification**
![Font Toggle Notification ja-0](https://user-images.githubusercontent.com/80428201/118889004-67c16700-b937-11eb-9819-d4c9e0f8e37c.png)

**Comment by cleidigh** [comment] 2021-05-19 23:49
@kiki-ja 
We need to use the toggle to match the toggle 'behavior of system option.
I think this logic makes more sense/fewer possible errors when using font
b3 will have your changes in tonight

**Comment by cleidigh** [comment] 2021-05-20 00:21
@RRoenn
@kiki-ja
@tidebre67 
@KC-T 
@madvinegar

b3  tonight should be good to go, unless something comes up I should be able to release
tomorrow

3 items other than the font issue:
- I changed the default border to 1.4px - solves the rendering missing the outline
- I removed the maximum TB version (+78 looks like it's working, but no guarantees)
- show  signature and vcf option/icons option

Christopher

**Comment by cleidigh** [comment] 2021-05-20 01:47
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.6/xpi/printing-tools-ng-2.0.6-b3-tb.xpi

**Comment by RRoenn** [comment] 2021-05-20 08:47
@cleidigh 
Sorry, I put a blank to much at the beginning after the line break before 'Schriftartenkontrolle'
wrong `Systemeinstellung:\n Schriftartenkontrolle`

please use
German:
```
1: alert("Systemeinstellung:\nSchriftartenkontrolle: Das Verwenden eigener Schriftarten\nwurde aktiviert");

0: alert("Systemeinstellung:\nSchriftartenkontrolle: Das Verwenden eigener Schriftarten\nwurde deaktiviert");

restore: alert("Systemeinstellung:\nSchriftartenkontrolle: Das Verwenden eigener Schriftarten\nwurde zurückgesetzt");
```
Just tested with the german local
Your hint for printing backgroundcolor is not clear. It is just necessary for the last option. There is too much space between the option and the hint, it looks like the hint is necessary for all options at this tab.

A better translation:
Hinweis: 'Hintergrund drucken (Farbe und Bilder)' muss im Dialogfeld 'Seite einrichten...' aktiviert sein

Greetings from germany

**Comment by RRoenn** [comment] 2021-05-20 09:15
@cleidigh 
I still have some spacing trouble with some mails, not just with the beta 

![spacing](https://user-images.githubusercontent.com/77779094/118952269-17103500-b95c-11eb-9fc0-9c56166d699a.PNG)

These mails are html-mails not just plain text

**Comment by tidebre67** [comment] 2021-05-20 12:17
> @cleidigh
> I still have some spacing trouble with some mails, not just with the beta
> 
> ![spacing](https://user-images.githubusercontent.com/77779094/118952269-17103500-b95c-11eb-9fc0-9c56166d699a.PNG)
> 
> These mails are html-mails not just plain text

@cleidigh , Christopher we had that issue already before and you solved it at that time.

**Comment by kiki-ja** [comment] 2021-05-20 12:24
@cleidigh 

> @kiki-ja
> We need to use the toggle to match the toggle 'behavior of system option.
> I think this logic makes more sense/fewer possible errors when using font
> b3 will have your changes in tonight

I understand.
Thanks.

**Comment by RRoenn** [comment] 2021-05-20 14:00
> 
> 
> @cleidigh
> and All.
> 
> Please let me know how I can translate it into Japanese.
> There are two terms.
> 
> [printingtoolsng.dtd]
> < !ENTITY showSignatureVCFfiles "Show **signature** and **vcf files**" >

sorry, I can't help. Maybe you get a clue looking at https://github.com/cleidigh/printing-tools-ng/issues/67 ?

**Comment by kiki-ja** [comment] 2021-05-20 17:12
@RRoenn 
@cleidigh 

Thank you very much.

I read #67, but I've never used OpenPGP or S/MINE (End-To-End Encryption), so I'm not sure.

In Thunderbird Account Settings, there are terms like 'digitally signed' and 'digital signature'.
This has to be distinguished from 'signature'.

Similarly, there is the term 'vCard'.
I'm not sure if I should use 'vCard' as 'vcf files' is not clear enough.

See the red and blue areas in the screenshot.

**End-To-End Encryption 1 - Account Settings (en-US)**
![End-To-End Encryption 1 - Account Settings](https://user-images.githubusercontent.com/80428201/119020360-1c5f9500-b9d9-11eb-9fdf-9d56b407255e.png)

**End-To-End Encryption 2 - Account Settings (en-US)**
![End-To-End Encryption 2 - Account Settings](https://user-images.githubusercontent.com/80428201/119020388-22557600-b9d9-11eb-8f71-e2f9401fd16b.png)

**vCard - Account Settings (en-US)**
![vCard - Account Settings](https://user-images.githubusercontent.com/80428201/119020408-284b5700-b9d9-11eb-8ffa-7f52ebe4417c.png)

**Comment by cleidigh** [comment] 2021-05-20 20:26
@kiki-ja 
this was a previously hidden option. the signature files are public keys
.p7m .p7s and possibly other future types.
you can use vCard if you prefer

**Comment by cleidigh** [comment] 2021-05-20 20:37
> @cleidigh
> Sorry, I put a blank to much at the beginning after the line break before 'Schriftartenkontrolle'
> wrong `Systemeinstellung:\n Schriftartenkontrolle`
> 
> please use
> German:
> 
> 
> ```
> 1: alert("Systemeinstellung:\nSchriftartenkontrolle: Das Verwenden eigener Schriftarten\nwurde aktiviert");
> 
> 0: alert("Systemeinstellung:\nSchriftartenkontrolle: Das Verwenden eigener Schriftarten\nwurde deaktiviert");
> 
> restore: alert("Systemeinstellung:\nSchriftartenkontrolle: Das Verwenden eigener Schriftarten\nwurde zurückgesetzt");
> ```
> 
> Just tested with the german local
> Your hint for printing backgroundcolor is not clear. It is just necessary for the last option. There is too much space between the option and the hint, it looks like the hint is necessary for all options at this tab.
> 
> A better translation:
> Hinweis: 'Hintergrund drucken (Farbe und Bilder)' muss im Dialogfeld 'Seite einrichten...' aktiviert sein
> 
> Greetings from germany

@RRoenn  thanks I will improve these
I understand and agree with making note closer
also I realized I did not completely match the option from the dialogue
Christopher

**Comment by cleidigh** [comment] 2021-05-20 20:50
@tidebre67 
@RRoenn 
@kiki-ja 
all right, I  have finally had enough with the header spacing!
so everyone understands it is the problem of a fixed table to control overflow
 and disables the autosize capability.
I have to implement a method to measure the longest header  and use that for spacing
Regardless of locale/font size
this will take a little bit ,But it should finally optimize the spacing in all scenarios
Christopher

**Comment by cleidigh** [comment] 2021-05-23 06:04
all
okay this does a lot.  I finally implemented real dynamic sizing for the header width.
now sizes to the maximum visible header regardless of locale with a 12px pad
I use a temporary table to accomplish this
I also improved several of the icon alignments
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.6/xpi/printing-tools-ng-2.0.6-b4-tb.xpi

![image](https://user-images.githubusercontent.com/25272315/119249893-5f04a700-bb6a-11eb-934e-084c045fd3a1.png)

![image](https://user-images.githubusercontent.com/25272315/119250019-244f3e80-bb6b-11eb-9317-838ff5f15f19.png)


![image](https://user-images.githubusercontent.com/25272315/119249642-34195380-bb68-11eb-802a-aab16a8d159a.png)

**Comment by cleidigh** [comment] 2021-05-23 06:07
@RRoenn 
I still have to put in your tweaks...

**Comment by cleidigh** [comment] 2021-05-23 06:23
all
I'm going to go ahead and implement the suggested option for cc & bcc
the option:
`Use 'cc' and 'bcc' abbreviations for all locales`

translations welcome.
@kiki-ja can you remind me  what localized cc/bcc for Japanese would be?
Christopher

**Comment by kiki-ja** [comment] 2021-05-24 03:22
@cleidigh 

Real dynamic sizing for the header width is fine on ja locale.

![dynamic sizing for the header width](https://user-images.githubusercontent.com/80428201/119292085-aa15db80-bc8a-11eb-809f-8bc04480a6f6.png)

**Comment by kiki-ja** [comment] 2021-05-24 03:23
@cleidigh 


> @kiki-ja can you remind me what localized cc/bcc for Japanese would be?

Is it the same as 'Please make all headers localizable (L10n)' #50?
Do I need to edit headers-ja.properties?

**Comment by cleidigh** [comment] 2021-05-24 03:38
@kiki-ja 
the logic I now have allows alternates specifically for cc and bcc
the next version will have the option to always use the abbreviations
everything else stays the same
I just need the appropriate translations, I will figure out where to put them
no need to   for you to edit

**Comment by cleidigh** [comment] 2021-05-24 03:45
With b5 you can force to use cc/bcc
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.6/xpi/printing-tools-ng-2.0.6-b5-tb.xpi
you can see this if you use German you can switch to be abbreviations

**Comment by tidebre67** [comment] 2021-05-24 11:19
> With b5 you can force to use cc/bcc
> https://github.com/cleidigh/printing-tools-ng/blob/v2.0.6/xpi/printing-tools-ng-2.0.6-b5-tb.xpi
> you can see this if you use German you can switch to be abbreviations

@cleidigh, Christopher, i think there is a small bug as date, from, to, copie (cc) and subject are double in b5. Pls see below.

![image](https://user-images.githubusercontent.com/44371934/119339966-22cc6600-bc92-11eb-9eb0-31a6f2f3e511.png)
![image](https://user-images.githubusercontent.com/44371934/119340310-a7b77f80-bc92-11eb-8ca4-2f396c576d3b.png)

**Comment by cleidigh** [comment] 2021-05-24 16:39
@tidebre67 
I messed up and no remove the shadow table
Focusing on the other sizing
did you try the new option ,,?
Christopher

**Comment by tidebre67** [comment] 2021-05-24 17:39
@cleidigh 
guess you ask about this new function:
![image](https://user-images.githubusercontent.com/44371934/119385944-29c19b80-bcc7-11eb-833b-e72890d36bcf.png)

yes, i did and works brilliant. 
Thomas

**Comment by cleidigh** [comment] 2021-05-24 20:41
b6 fixes and removes the shadow table
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.6/xpi/printing-tools-ng-2.0.6-b6-tb.xpi

**Comment by KC-T** [comment] 2021-05-25 04:05
The "Cc" line has been moved to the last row when using the new use 'Cc' option.
![Screen Shot 05-25-21 at 12 02 PM](https://user-images.githubusercontent.com/81372892/119437660-2ffc5a00-bd51-11eb-96d0-7077659ef974.PNG)

The "CC" line is in the custom defined order without clicking the new use "Cc" option.
![Screen Shot 05-25-21 at 12 03 PM](https://user-images.githubusercontent.com/81372892/119437703-460a1a80-bd51-11eb-81d4-422027ba1d0d.PNG)

Please adjust.

K C

**Comment by cleidigh** [comment] 2021-05-25 04:43
I have observed this
I have fixed it
just need the Japanese translations for Cc and Bcc

**Comment by cleidigh** [comment] 2021-05-25 04:49
@KC-T 
I assume you are using b6
which locale?
this should be fixed already..?

**Comment by cleidigh** [comment] 2021-05-25 04:55
My error, b7 will have fix
will post shortly

**Comment by cleidigh** [comment] 2021-05-25 04:58
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.6/xpi/printing-tools-ng-2.0.6-b7-tb.xpi

**Comment by KC-T** [comment] 2021-05-25 05:12
I have used b7 now. The row order is now right. I am using English (UK) locale.

I have tested Chinese (mainland) locale. No effect at all. On the other hand, this new feature is not essential for Chinese.

As a side issue, the "From" word has not been translated to Chinese when using Printing Tool, while Thunderbird shows it in Chinese.

**Comment by cleidigh** [comment] 2021-05-25 05:17
I noticed the  Chinese as well
this is a TB  issue I have to correct
essentially there are many locales with Header localization errors

**Comment by kiki-ja** [comment] 2021-05-25 11:11
@cleidigh 

The header 'attachments' line is broken.
Is this a problem with 'real dynamic sizing for the header width'?

Steps to reproduce: 
１．PrintingTools NG 2.0.6 b7
２. ja (Japanese) locale only
３. Options -> Style
　　'Use fonts with a size in pixel of xxxxx with size xxx' = unchecked (off)

Please see the screenshot.

[Headers line break]
![2 0 6 b7 header line break](https://user-images.githubusercontent.com/80428201/119488255-4cba8100-bd95-11eb-855f-5a21ae15aa82.png)

**Comment by cleidigh** [comment] 2021-05-25 23:59
@kiki-ja 
so far I cannot reproduce the attachment line break
below is a screenshot and debug console output if you can post to that as well
I may be able to figure out
I am thinking some other option is causing the problem
an e-mail Closely matching yours

![image](https://user-images.githubusercontent.com/25272315/119582854-63f86f00-bd93-11eb-85bc-21b56ba877ec.png)

```txt
<td style="vertical-align: top;"><div class="headerdisplayname" style="display:inline;">送信日時: </div></td>
送信日時: 
0 2
<td id="receivedDate" style="vertical-align: top;"><span><b>受信日時: </b></span></td>
受信日時: 
0 2
<td style="vertical-align: top;"><div class="headerdisplayname" style="display:inline;">宛先: </div></td>
宛先: 
0 2
<td style="vertical-align: top;"><div class="headerdisplayname" style="display:inline;">差出人: </div></td>
差出人: 
0 2
<td style="vertical-align: top;"><div class="headerdisplayname subjectHdr" style="display:inline;">件名: </div></td>
件名: 
0 2
<td style="vertical-align: top;"><div class="headerdisplayname" style="display:inline;">Cc: </div></td>
Cc: 
0 2
<td class="bccHdr" style="vertical-align: top;"><div class="headerdisplayname" style="display:inline;">Bcc: </div></td>
Bcc: 
0 2
<td style="vertical-align: top;"><span id="spanTD" class="attHdr"><b>添付ファイル: </b></span></td>
添付ファイル: 
0 2
112
<html><head>
<title>printing tools sizing test</title>
<link rel="important stylesheet" href="chrome://messagebody/skin/messageBody.css">
</head>
<body>
<h3>printing tasks and</h3><table class="header-part1" style="table-layout: fixed; margin-right: 10px; border: 2px solid blue; background-color: rgb(128, 255, 255);" width="100%" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td style="vertical-align: top; padding: 3px 0px 0px 6px;" width="111px"><div class="headerdisplayname" style="display: inline; padding-right: 0px;">送信日時: </div></td><td style="padding: 0px 0px 0px 6px;">2021年5月25日(火) 16:26</td></tr><tr id="recTR"><td id="receivedDate" style="vertical-align: top; padding: 0px 0px 0px 6px;" width="111px"><span style="padding-right: 0px;"><b>受信日時: </b></span></td><td style="padding: 0px 0px 0px 6px;">2021年5月25日(火) 16:26</td></tr><tr><td style="vertical-align: top; padding: 0px 0px 0px 6px;" width="111px"><div class="headerdisplayname" style="display: inline; padding-right: 0px;">宛先: </div></td><td style="padding: 0px 0px 0px 6px;">test1@kokkini.net</td></tr><tr><td style="vertical-align: top; padding: 0px 0px 0px 6px;" width="111px"><div class="headerdisplayname" style="display: inline; padding-right: 0px;">差出人: </div></td><td style="padding: 0px 0px 0px 6px;">Christopher Leidigh &lt;test1@kokkini.net&gt;</td></tr><tr><td style="vertical-align: top; padding: 0px 0px 0px 6px;" width="111px"><div class="headerdisplayname subjectHdr" style="display: inline; padding-right: 0px; float: left;">件名: </div></td><td style="padding: 0px 0px 0px 6px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;"><div style="overflow: hidden; white-space: nowrap; padding-right: 0px;">printing tools sizing test</div></td></tr><tr><td style="vertical-align: top; padding: 0px 0px 0px 6px;" width="111px"><div class="headerdisplayname" style="display: inline; padding-right: 0px;">Cc: </div></td><td style="padding: 0px 0px 0px 6px;">test1@kokkini.net, test1@kokkini.net, Christopher Leidigh &lt;test1@kokkini.net&gt;, Christopher Leidigh &lt;test1@kokkini.net&gt;</td></tr><tr><td class="bccHdr" style="vertical-align: top; padding: 0px 0px 0px 6px;" width="111px"><div class="headerdisplayname" style="display: inline; padding-right: 0px;">Bcc: </div></td><td style="padding: 0px 0px 0px 6px;">Christopher Leidigh &lt;test1@kokkini.net&gt;, Christopher Leidigh &lt;test1@kokkini.net&gt;, Christopher Leidigh &lt;test1@kokkini.net&gt;</td></tr><tr id="attTR"><td style="vertical-align: top; padding: 0px 0px 0px 6px;" width="111px"><span id="spanTD" class="attHdr" style="padding-right: 0px;"><b>添付ファイル: </b></span></td><td id="attTD" style="padding: 0px 8px 0px 6px; overflow: hidden; overflow-wrap: break-word;"><div style="overflow-wrap: break-word; word-wrap: break-word; "><div style="overflow-wrap: break-word; padding-right: 0px;"><span style="padding-left: 16px; word-wrap: nowrap; position: relative;"><img src="resource://printingtoolsng/icons/png.gif" class="attIcon" style="position: absolute; bottom: 2px; left: 0px" width="16px" height="16px">&nbsp;printing-tools-ng-icon-64px - Copy hello hello hello hello hello hello hello hello hello hello - Copyhello hello hello hello hello hello picture.png&nbsp;(3.6 KB)</span></div></div></td></tr></tbody></table><table class="header-part2" style="display: none; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 1px solid black;" width="100%" cellspacing="0" cellpadding="0" border="0"><tbody></tbody></table><br>
<div class="moz-text-flowed" style="font-family: -moz-fixed; font-size: 14px;" lang="x-unicode">
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br></div><br><div class="moz-attached-image-container"><img class="moz-attached-image" shrinktofit="yes" src="mailbox:///C:/Dev/Thunderbird/Profiles/Test78-x2/Mail/secure33.webhostinghub.com/Sent?number=36&amp;header=print&amp;part=1.2&amp;type=image/png&amp;filename=printing-tools-ng-icon-64px%20-%20Copy%20hello%20hello%20hello%20hello%20hello%20hello%20hello%20hello%20hello%20hello%20-%20Copyhello%20hello%20hello%20hello%20hello%20hello%20picture.png" style="height:auto; width:auto; max-width:100%; max-height:100%;"></div>

<br><div class="mimeAttachmentWrap"></div></body></html>
```

**Comment by cleidigh** [comment] 2021-05-26 00:01
Also if you have the Japanese localizations for:
Cc
Bcc

**Comment by cleidigh** [comment] 2021-05-26 00:02
you can also try b6 which shows the sizing table
along with this console output

**Comment by cleidigh** [comment] 2021-05-26 01:32
@kiki-ja 
b5 is the version that shows the shadow table

**Comment by kiki-ja** [comment] 2021-05-26 12:22
@cleidigh 

Attach console logs, compared text, configuration information, test sample message files, and screenshots.
Hope this helps.

**console log**
[console-export-2021-5-26 kiki-ja.txt](https://github.com/cleidigh/printing-tools-ng/files/6546604/console-export-2021-5-26.kiki-ja.txt)

**compiler text**
[Console Comparison cleidigh and kiki-ja.txt](https://github.com/cleidigh/printing-tools-ng/files/6546612/Console.Comparison.cleidigh.and.kiki-ja.txt)

**compiler text screenshot**
![Console Comparison cleidigh and kiki-ja](https://user-images.githubusercontent.com/80428201/119658679-6678c880-be68-11eb-8c9d-d9f35adb75cb.png)

**Comment by cleidigh** [comment] 2021-05-26 22:13
@kiki-ja 
I think I see part of the issue the first, col is calculating incorrectly
somehow the attachment is not utilized for the calculation
the width in yours is 99px  should be close to 110
It might be a font difference
			<tr id="attTR">
				<td style="vertical-align: top; padding: 0px 0px 0px 6px;" width="99px"><span id="spanTD" class="attHdr"
						style="padding-right: 0px;"><b>添付ファイル: </b></span></td>
				<td id="attTD" style="padding: 0px 8px 0px 6px;">
					<div style="overflow-wrap: break-word; word-wrap: break-word; ">
						<div style="overflow-wrap: break-word; padding-right: 0px;"><span

I doubt you will see this before much later,but if you do
maybe I can send you more console.debug
I just cannot reproduce the linebreaks

**Comment by cleidigh** [comment] 2021-05-26 22:56
okay
it looks like b4 'worked and b5 does not
can you check the console output for both?
I still think it is an option issue however that does not explain everything

**Comment by cleidigh** [comment] 2021-05-27 04:04
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.6/xpi/printing-tools-ng-2.0.6-b7t1-tb.xpi

try this test,capture screenshot,console.debug

**Comment by cleidigh** [comment] 2021-05-27 04:05
![image](https://user-images.githubusercontent.com/25272315/119764367-3ee12a80-be7f-11eb-8d9c-2050f9033c14.png)

**Comment by cleidigh** [comment] 2021-05-27 04:54
Name === nothing
![image](https://user-images.githubusercontent.com/25272315/119767904-c2057f00-be85-11eb-84c2-6a2ea745ad49.png)

![image](https://user-images.githubusercontent.com/25272315/119767983-df3a4d80-be85-11eb-9163-89c3349a176a.png)

With name
![image](https://user-images.githubusercontent.com/25272315/119768095-0ee95580-be86-11eb-9ca4-f12fec822702.png)

**Comment by kiki-ja** [comment] 2021-05-27 21:09
@cleidigh 

I tested it with 2.0.6 b7t1.
The results are as follows.
I've attached a screenshot and the console log.
 
 
**2.0.7 b7t1 Style - Font off**
![2 0 7 b7t1 Style - Font off](https://user-images.githubusercontent.com/80428201/119896602-34578b80-bf7a-11eb-9908-9d23c4bb51df.png)
 
**Option - Style - Font off**
![Style - Font off](https://user-images.githubusercontent.com/80428201/119896665-4df8d300-bf7a-11eb-932c-514c2f8c6993.png)
 
**console-log 207b7t1 font off**
[console-log 207b7t1 font off.txt](https://github.com/cleidigh/printing-tools-ng/files/6556809/console-log.207b7t1.font.off.txt)
 
ーーーーーーーーーーーーーーーーーーーーーーーーーーーー
**2.0.7 b7t1 Style - Font on**
![2 0 7 b7t1 Style - Font on](https://user-images.githubusercontent.com/80428201/119896692-58b36800-bf7a-11eb-8e96-4a1f80775c93.png)
 
**Option - Style - Font on**
![Style - Font on](https://user-images.githubusercontent.com/80428201/119896711-5fda7600-bf7a-11eb-9b70-229cc7352ae2.png)
 
**console-log 207b7t1 font on**
[console-log 207b7t1 font on.txt](https://github.com/cleidigh/printing-tools-ng/files/6556810/console-log.207b7t1.font.on.txt)

**Comment by kiki-ja** [comment] 2021-05-27 21:18
@cleidigh 

I use a font called 'BIZ UDP ゴシック' regularly.
I have it set as my system font in Windows 10.
Thunderbird also has this font set for display.
This font is a popular font in Windows 10 Japanese version.

**Comment by cleidigh** [comment] 2021-05-27 22:08
@kiki-ja 
excellent!
I just fixed the Chinese from
I should be able to post a pretty clean version
I still could use translations for cc/bcc if you want Japanese versions

**Comment by kiki-ja** [comment] 2021-05-27 22:49
@cleidigh 

> I still could use translations for cc/bcc if you want Japanese versions

I would like to keep the "Cc/Bcc" translation.
The reason for this is that I want it to match the localization of Thunderbird.
In the Japanese version of Thunderbird, "Cc/Bcc" is displayed as it is.

Please see the screenshots.
 
**Messages Composer Window (ja)**
![Messages Composer Window](https://user-images.githubusercontent.com/80428201/119905872-01b48f80-bf88-11eb-9f83-1aeb7419480f.png)
 
**Message Header & Pain (ja)**
![Message Header   Pain](https://user-images.githubusercontent.com/80428201/119905887-08430700-bf88-11eb-8483-8a50f34d01dd.png)

**Comment by cleidigh** [comment] 2021-05-27 23:32
sounds good!
I really appreciate all of your testing time, I still wish I could reproduce that line break
I have a feeling it was a small change because of the font perhaps
now for cleanup

**Comment by cleidigh** [comment] 2021-05-29 03:57
@RRoenn
@kiki-ja
@tidebre67 
@KC-T 
@madvinegar

v2.0.6 has been posted to the Q
I  summarize  tomorrow
thanks all
Christopher

https://github.com/cleidigh/printing-tools-ng/blob/v2.0.6/xpi/printing-tools-ng-2.0.6-tb.xpi

**Comment by cleidigh** [comment] 2021-05-29 22:16
well it is already released, make sure you update
I also updated the extension details for German and Japanese users


Version 2.0.6 : 68/78/89+ Update - May 29, 2021

- Allow compatibility to 89+ (experimental support only) #66
- Add option: Use 'Cc' and 'Bcc' for all locales (otherwise localized)
- Make header dynamically sized to largest item
- Add option #67: Show p7m,p7s,vcf files
- Add debug option : use 'initialsource' and/or 'finaloutput' 
  in custom name field for output
- Fix #69  Set system option to allow custom fonts, inform user
- Fix 'From' in Chinese locale
- Various German, Japanese locale improvements

Again thanks for testers/localizers:
@RRoenn
@kiki-ja
@tidebre67 
@KC-T 
@madvinegar

**Comment by kiki-ja** [comment] 2021-05-29 23:37
@cleidigh 

I've attached the 2.0.6 changelog to #48.
Please use it.

**Comment by cleidigh** [comment] 2021-05-31 22:42
@kiki-ja 
I updated the English to make sure all lines were terminated with a .
I then used your intro/changelog and translated
details with Google.
here's what I posted:

[description.txt](https://github.com/cleidigh/printing-tools-ng/files/6572434/description.txt)

[Japanese description.txt](https://github.com/cleidigh/printing-tools-ng/files/6572436/Japanese.description.txt)

**Comment by kiki-ja** [comment] 2021-06-02 01:18
@cleidigh 

I have uploaded and attached the updated translation text to #48.

**Closed** 2022-03-04 16:18 UTC
