### ISSUE TITLE
PrintingToolsNg cant find printer

### ISSUE THREAD

**Issue by penkii123456** [cleidigh/printing-tools-ng#25] opened 2021-01-30 23:38 UTC
I had an TPV computer, it works with W7, the printer is correctly installed cuz i can print from windows, the problem comes when i want to Add-On Options, to configure the rules for automatic printing when there is an order from the OnlineShop, but the plugin cant find it, and idk what to do honestly, tried most of things even the drivers but nothing happened.

Images:
https://www.dropbox.com/sh/n4l0vw1pkdd8usq/AAAYl85rRKIJrN4LClrit7Uba?dl=0

**Comment by cleidigh** [comment] 2021-01-31 22:17
@penkii123456 
thanks for the post,sorry for the issue.
I believe I have seen this before ,but not repeated it.
from the first screenshot the option dropdown is empty
if I remember correctly the issue for me went away 
after I brought up the printers when I went to "File/Print"
and set a default printer there
do you see full the printer list there?
then go back to the options to see the list is populated
Christopher

**Comment by penkii123456** [comment] 2021-01-31 22:47
Hi cleidigh, its fixed already, all i did is print manually in thunderbird, after that it popped up all the printers.

btw do you know any pluggin to config the size letter of the ticket itself? 

thanks for your time.

**Comment by cleidigh** [comment] 2021-01-31 23:02
@penkii123456 
this is definitely a bug, I have to reproduce it...
your last question I am not sure I'm totally clear,
are you asking about changing the font size or page size?
use the regular print options for the page size
you can set the font family and size under style tab
![image](https://user-images.githubusercontent.com/25272315/106400745-669f1500-63ee-11eb-9596-cd0edc02a3f9.png)

Christopher

**Comment by cleidigh** [comment] 2021-02-01 00:47
@penkii123456 
the issue was no default printer on fresh installs
I have a fix in v2.0.1-b4 four  which will be released shortly
unless you start fresh again ,you will not be able to reproduce.
Christopher

https://github.com/cleidigh/printing-tools-ng/blob/v2.0.1/xpi/printing-tools-ng-2.0.1-b4-tb.xpi

**Comment by penkii123456** [comment] 2021-02-01 23:57
Hi! Ty for the fix really appreciate it.
Btw i tried to config the tickets in the way that you suggested, but it doesn´t work literally, there are any other way to try to config it?
Cheers Christopher.

**Comment by cleidigh** [comment] 2021-02-02 00:47
@penkii123456 
I think I need a clear description of `ticket`  as what you're trying to adjust
so I can hopefully suggest something else.

**Comment by penkii123456** [comment] 2021-02-02 23:08
Hi cleidigh! The ticket print format is the typical TPV printer 80mm. I added 2 photos of it so i can let you take an look instead of writting it.
TY in advance.

https://www.dropbox.com/sh/3lyp8nv6d2v7to1/AAAqr_t9hUDU0yW4TOP--EBoa?dl=0

**Comment by cleidigh** [comment] 2021-02-03 00:25
@penkii123456 
okay I understand the final product, a food order ticket.
What I need to also know is where does the ticket, from? What software?
how does the ticket get into Thunderbird?  I assume it's a formatted email?
can you send me an example e-mail/ticket?
is this something new or have you done it before?
Christopher

**Comment by penkii123456** [comment] 2021-02-03 00:56
I had an Wordpress website, it uses woocommerce platform, and from the website, customers can make an online-order delivery and directly pay it.
When the customer ends making an order, the website automatically sends an mail with the info-order.
So i used Thunderbird and bind the restaurant mail with, used ur video tutorial from that point and configured it as you did in the tutorial, so everytime when there are any order, it automatically prints the ticket and can also in the sametime notify me.(already working)
So now the problem is the format of the food order ticket, it just looks like "incomplete".
Yes it prints directly from the mail order format. 
It's something new that im trying as an posible solution (still not definitely), otherwise all i could do its use an phone, bind the restaurant mail in, and connect it with an bluetooth speaker, and let it notify me everytime there are an online order.

PD: Appreciate ur time and help CHEERS.

**Comment by cleidigh** [comment] 2021-02-03 01:01
@penkii123456 
okay were getting closer, what tutorial are you referring to,I do not have any?
questions:
what makes the incoming e-mail automatically printed?
can you forward me an example ticket e-mail?
test1@kokkini.net
Christopher

**Comment by penkii123456** [comment] 2021-02-03 01:05
https://www.dropbox.com/s/vh1you1eiwv5i82/Captura.PNG?dl=0
Example ticket email order.
Tutorial video: 
https://www.youtube.com/watch?v=8qIafd4xLgg&t=91s&ab_channel=GeorgiBakalski

PS: Ops i tought you were the same guy from the tutorial, my bad.

**Comment by cleidigh** [comment] 2021-02-03 01:19
can you e-mail me the actual ticketnot a picture
use the following email
test1@kokkini.net

I will also look at the tutorial
I think the issue is you are not printing HTML so you loose the color and tables

**Comment by penkii123456** [comment] 2021-02-03 01:24
Already sent mate.

"I think the issue is you are not printing HTML so you loose the color and tables" - I see, there are any way to fix it?

**Comment by cleidigh** [comment] 2021-02-03 01:26
okay I will go to account
we may find it easier to solve this with a chat/z0om
because I'm disabled talking this a lot easier than dictation text
where are you located,Spain?

Christopher

**Comment by penkii123456** [comment] 2021-02-03 01:29
Yeap, im located in Spain, yea we can go for an chat so its alot easier to talk eachother

**Comment by cleidigh** [comment] 2021-02-03 01:36
I just took a look at the forward
it looks like the e-mail as both a text and HTML
it must be printing the text By default.
for more clarity can you do the following:
open a ticket e-mail in Thunderbird
then press   control-u to get a source window
then copy and paste here I'm trying to see the true and 
mail
if I can reproduce issue I can better direct you
otherwise will find a good time for both of us to talk

**Comment by penkii123456** [comment] 2021-02-03 01:57
Return-Path: <gransiglomadrid@gmail.com>
Received: from www.gransiglomadrid.com (cp702.webempresa.eu. [51.91.61.210])
        by smtp.gmail.com with ESMTPSA id b13sm22921785wrt.31.2021.01.31.10.48.50
        for <gransiglomadrid@gmail.com>
        (version=TLS1_2 cipher=ECDHE-ECDSA-AES128-GCM-SHA256 bits=128/128);
        Sun, 31 Jan 2021 10:48:50 -0800 (PST)
Date: Sun, 31 Jan 2021 18:48:49 +0000
To: gransiglomadrid@gmail.com
From: Gran Siglo Madrid <gransiglomadrid@gmail.com>
Subject: Has registrado un nuevo pedido
Message-ID: <D6954ix6AGwwJgUe2fIVweJHJpt4EDlkMuyakzTTA8@www.gransiglomadrid.com>
X-Mailer: PHPMailer 6.2.0 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit

<!DOCTYPE html>
<html lang="es">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Gran Siglo</title>
</head>
<body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0" style="padding: 0;">
		<div id="wrapper" dir="ltr" style="background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%; -webkit-text-size-adjust: none;">
			<table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%">
<tr>
<td align="center" valign="top">
						<div id="template_header_image">
													</div>
						<table border="0" cellpadding="0" cellspacing="0" width="600" id="template_container" style="background-color: #ffffff; border: 1px solid #dedede; box-shadow: 0 1px 4px rgba(0, 0, 0, 0.1); border-radius: 3px;">
<tr>
<td align="center" valign="top">
									
									<table border="0" cellpadding="0" cellspacing="0" width="100%" id="template_header" style='background-color: #96588a; color: #ffffff; border-bottom: 0; font-weight: bold; line-height: 100%; vertical-align: middle; font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif; border-radius: 3px 3px 0 0;'><tr>
<td id="header_wrapper" style="padding: 36px 48px; display: block;">
												<h1 style='font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif; font-size: 30px; font-weight: 300; line-height: 150%; margin: 0; text-align: left; text-shadow: 0 1px 0 #ab79a1; color: #ffffff; background-color: inherit;'>NUEVA ORDEN</h1>
											</td>
										</tr></table>

</td>
							</tr>
<tr>
<td align="center" valign="top">
									
									<table border="0" cellpadding="0" cellspacing="0" width="600" id="template_body"><tr>
<td valign="top" id="body_content" style="background-color: #ffffff;">
												
												<table border="0" cellpadding="20" cellspacing="0" width="100%"><tr>
<td valign="top" style="padding: 48px 48px 32px;">
															<div id="body_content_inner" style='color: #636363; font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif; font-size: 14px; line-height: 150%; text-align: left;'>

<p style="margin: 0 0 16px;">Has recibido el siguiente pedido de  :</p>

<h2 style='color: #96588a; display: block; font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif; font-size: 18px; font-weight: bold; line-height: 130%; margin: 0 0 18px; text-align: left;'>
	<a class="link" href="https://www.gransiglomadrid.com/wp-admin/post.php?post=1570&amp;action=edit" style="font-weight: normal; text-decoration: underline; color: #96588a;">[Pedido #1570]</a> (31 enero, 2021)</h2>

<div style="margin-bottom: 40px;">
	<table class="td" cellspacing="0" cellpadding="6" border="1" style="color: #636363; border: 1px solid #e5e5e5; vertical-align: middle; width: 100%; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;">
<thead><tr>
<th class="td" scope="col" style="color: #636363; border: 1px solid #e5e5e5; vertical-align: middle; padding: 12px; text-align: left;">Producto</th>
				<th class="td" scope="col" style="color: #636363; border: 1px solid #e5e5e5; vertical-align: middle; padding: 12px; text-align: left;">Cantidad</th>
				<th class="td" scope="col" style="color: #636363; border: 1px solid #e5e5e5; vertical-align: middle; padding: 12px; text-align: left;">Precio</th>
			</tr></thead>
<tbody>
<tr class="order_item">
<td class="td" style="color: #636363; border: 1px solid #e5e5e5; padding: 12px; text-align: left; vertical-align: middle; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif; word-wrap: break-word;">
		10. Patatas fritas		</td>
		<td class="td" style="color: #636363; border: 1px solid #e5e5e5; padding: 12px; text-align: left; vertical-align: middle; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;">
			1		</td>
		<td class="td" style="color: #636363; border: 1px solid #e5e5e5; padding: 12px; text-align: left; vertical-align: middle; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;">
			<span class="woocommerce-Price-amount amount">3.45<span class="woocommerce-Price-currencySymbol">a??</span></span>		</td>
	</tr>
<tr class="order_item">
<td class="td" style="color: #636363; border: 1px solid #e5e5e5; padding: 12px; text-align: left; vertical-align: middle; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif; word-wrap: break-word;">
		104. Pollo sobre bandeja quemada		</td>
		<td class="td" style="color: #636363; border: 1px solid #e5e5e5; padding: 12px; text-align: left; vertical-align: middle; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;">
			1		</td>
		<td class="td" style="color: #636363; border: 1px solid #e5e5e5; padding: 12px; text-align: left; vertical-align: middle; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;">
			<span class="woocommerce-Price-amount amount">7.65<span class="woocommerce-Price-currencySymbol">a??</span></span>		</td>
	</tr>
<tr class="order_item">
<td class="td" style="color: #636363; border: 1px solid #e5e5e5; padding: 12px; text-align: left; vertical-align: middle; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif; word-wrap: break-word;">
		109. Ternera sobre bandeja quemada con puerros		</td>
		<td class="td" style="color: #636363; border: 1px solid #e5e5e5; padding: 12px; text-align: left; vertical-align: middle; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;">
			1		</td>
		<td class="td" style="color: #636363; border: 1px solid #e5e5e5; padding: 12px; text-align: left; vertical-align: middle; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;">
			<span class="woocommerce-Price-amount amount">7.65<span class="woocommerce-Price-currencySymbol">a??</span></span>		</td>
	</tr>
<tr class="order_item">
<td class="td" style="color: #636363; border: 1px solid #e5e5e5; padding: 12px; text-align: left; vertical-align: middle; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif; word-wrap: break-word;">
		112. Pato a la pekinesa		</td>
		<td class="td" style="color: #636363; border: 1px solid #e5e5e5; padding: 12px; text-align: left; vertical-align: middle; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;">
			1		</td>
		<td class="td" style="color: #636363; border: 1px solid #e5e5e5; padding: 12px; text-align: left; vertical-align: middle; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;">
			<span class="woocommerce-Price-amount amount">12.50<span class="woocommerce-Price-currencySymbol">a??</span></span>		</td>
	</tr>
</tbody>
<tfoot>
<tr>
<th class="td" scope="row" colspan="2" style="color: #636363; border: 1px solid #e5e5e5; vertical-align: middle; padding: 12px; text-align: left; border-top-width: 4px;">Subtotal:</th>
						<td class="td" style="color: #636363; border: 1px solid #e5e5e5; vertical-align: middle; padding: 12px; text-align: left; border-top-width: 4px;"><span class="woocommerce-Price-amount amount">31.25<span class="woocommerce-Price-currencySymbol">a??</span></span></td>
					</tr>
<tr>
<th class="td" scope="row" colspan="2" style="color: #636363; border: 1px solid #e5e5e5; vertical-align: middle; padding: 12px; text-align: left;">M??todo de pago:</th>
						<td class="td" style="color: #636363; border: 1px solid #e5e5e5; vertical-align: middle; padding: 12px; text-align: left;">Efectivo</td>
					</tr>
<tr>
<th class="td" scope="row" colspan="2" style="color: #636363; border: 1px solid #e5e5e5; vertical-align: middle; padding: 12px; text-align: left;">Total:</th>
						<td class="td" style="color: #636363; border: 1px solid #e5e5e5; vertical-align: middle; padding: 12px; text-align: left;"><span class="woocommerce-Price-amount amount">31.25<span class="woocommerce-Price-currencySymbol">a??</span></span></td>
					</tr>
</tfoot>
</table>
</div>


<table id="addresses" cellspacing="0" cellpadding="0" border="0" style="width: 100%; vertical-align: top; margin-bottom: 40px; padding: 0;"><tr>
<td valign="top" width="50%" style="text-align: left; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif; border: 0; padding: 0;">
			<h2 style='color: #96588a; display: block; font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif; font-size: 18px; font-weight: bold; line-height: 130%; margin: 0 0 18px; text-align: left;'>Direcci?3n de facturaci?3n</h2>

			<address class="address" style="padding: 12px; color: #636363; border: 1px solid #e5e5e5;">
				N/D											</address>
		</td>
			</tr></table>
<p style="margin: 0 0 16px;">Enhorabuena por la venta.</p>
															</div>
														</td>
													</tr></table>

</td>
										</tr></table>

</td>
							</tr>
</table>
</td>
				</tr>
<tr>
<td align="center" valign="top">
						
						<table border="0" cellpadding="10" cellspacing="0" width="600" id="template_footer"><tr>
<td valign="top" style="padding: 0; border-radius: 6px;">
									<table border="0" cellpadding="10" cellspacing="0" width="100%"><tr>
<td colspan="2" valign="middle" id="credit" style='border-radius: 6px; border: 0; color: #8a8a8a; font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif; font-size: 12px; line-height: 150%; text-align: center; padding: 24px 0;'>
												<p style="margin: 0 0 16px;">Gran Siglo</p>
											</td>
										</tr></table>
</td>
							</tr></table>

</td>
				</tr>
</table>
</div>
	</body>
</html>

**Comment by penkii123456** [comment] 2021-02-03 01:58
oke i already sent it to ur mail.

**Comment by cleidigh** [comment] 2021-02-03 02:11
okay
let me play with these and I may send you something to try printing
probably by tomorrow.  is the printer color and you really care about the color?
only asking because the header

**Comment by penkii123456** [comment] 2021-02-03 09:13
Hi, Its an black&white old printer so the color doesnt matter at all.

Ty for your attention and time Christopher. Have an nice day!

**Comment by cleidigh** [comment] 2021-02-03 20:53
here is a the preview
I think it's just a matter of some settings
let me know when you're online to discuss
Christopher
![image](https://user-images.githubusercontent.com/25272315/106808039-dfdd7880-6637-11eb-9687-2e7ff229f4dc.png)

**Comment by penkii123456** [comment] 2021-02-03 22:13
I see, what kind of setting is?

**Comment by cleidigh** [comment] 2021-02-03 22:22
okay let's try a few simple experiments
as far as I can tell  I can do a good Preview  with several of your examples
First I would disable FiltaQ temporarily 
try a PrintPreview and see whether looks like,try printing
poster capture here

**Comment by cleidigh** [comment] 2021-02-03 22:34
by the way you can Paste a screen capture from 6 Windows directly here

**Comment by penkii123456** [comment] 2021-02-03 22:51
i already disabled the FiltaQ and it prints in the same format, the computer  its an bit old so cant do an PrintPreview, just directly print, i was checking the format paper of the printer and its 80x297mm, in few minutes i will add some screens so you can have an idea of what im dealing with.

**Comment by penkii123456** [comment] 2021-02-03 22:58
![20210203_235305](https://user-images.githubusercontent.com/78283222/106820313-68c9d380-667b-11eb-828f-fffe07314e46.jpg)
![20210203_235340](https://user-images.githubusercontent.com/78283222/106820318-69fb0080-667b-11eb-854d-04a4bc7c42d9.jpg)
My problem is that i have to adjust the mail format into an ticket 80x297mm and it after being printed have to has all the content mail but in the ticket 80x297mm

**Comment by penkii123456** [comment] 2021-02-03 23:02
But as you can see in the photos, it just shows an half of the mail from the original format mail, and i would like to adjust the original format mail in the ticket of the printer completely.

**Comment by cleidigh** [comment] 2021-02-03 23:09
with your close-up I see table lines so I don't think we are far off
under the file menu cant you use  print preview ?

**Comment by cleidigh** [comment] 2021-02-03 23:11
also I think we can change the page margins under page Set up

**Comment by penkii123456** [comment] 2021-02-03 23:19
i found it  sending some screens righnow

**Comment by penkii123456** [comment] 2021-02-03 23:25
![Screenshot_1](https://user-images.githubusercontent.com/78283222/106822436-6ec1b380-667f-11eb-94c8-5c0192dbb9c2.png)
ticketpreview

**Comment by penkii123456** [comment] 2021-02-03 23:27
![Screenshot_2](https://user-images.githubusercontent.com/78283222/106822581-afb9c800-667f-11eb-9b39-f913e4cc7e1f.png)
![Screenshot_3](https://user-images.githubusercontent.com/78283222/106822587-b1838b80-667f-11eb-82cc-e29d2e9aa14b.png)

**Comment by cleidigh** [comment] 2021-02-03 23:30
okay that's pretty close
if you want we could chat now  on Zoom where you can share your screen

**Comment by penkii123456** [comment] 2021-02-03 23:32
oke, im using the restaurant computer, so it doesnt have high spec, nut we can try zoom, im installing it

**Comment by cleidigh** [comment] 2021-02-03 23:34
great
I will post and invite

**Comment by penkii123456** [comment] 2021-02-03 23:34
i already done it, what is the number of the chatroom?

**Comment by cleidigh** [comment] 2021-02-03 23:38
click the invitation
Christopher Leidigh is inviting you to a scheduled Zoom meeting.

Topic: My Meeting
Time: Feb 3, 2021 06:30 PM Eastern Time (US and Canada)

Join Zoom Meeting
https://us04web.zoom.us/j/79765999107?pwd=cThjcWNCSW44cXA1UXdjc3dndFFqZz09

Meeting ID: 797 6599 9107
Passcode: zFQ2fj

**Comment by penkii123456** [comment] 2021-02-03 23:40
i dont have camera or micro in the restaurant computer, can it be an chat?

**Comment by penkii123456** [comment] 2021-02-03 23:40
i can just write from this computer

**Comment by cleidigh** [comment] 2021-02-03 23:42
okay well just go back and forth here

**Comment by cleidigh** [comment] 2021-02-03 23:43
so I think we will make progress if we change the page size and margins

**Comment by cleidigh** [comment] 2021-02-03 23:45
go to FilePrint where we should see. Your printers
we want to go to set the page size

**Comment by cleidigh** [comment] 2021-02-03 23:46
![image](https://user-images.githubusercontent.com/25272315/106824101-12936b00-6650-11eb-9586-102d8f00a600.png)

**Comment by cleidigh** [comment] 2021-02-03 23:47
highlight your printer
select preferences
capture the screen and post you here

**Comment by penkii123456** [comment] 2021-02-03 23:47
Hi Christopher i already tried to configure it and it got the ideal size that i wanted, so its already solved, really appreciate ur time, hardwork and specially attention. CHERS

**Comment by cleidigh** [comment] 2021-02-03 23:48
okay great!

**Closed** 2021-02-03 23:47 UTC
