### ISSUE TITLE
PTNG fails when [To] header is missing

### ISSUE THREAD

**Issue by KC-T** [cleidigh/printing-tools-ng#79] opened 2021-07-08 18:26 UTC
If the "To" field of the incoming email is empty, no border will be printed around the headers.

**Comment by kiki-ja** [comment] 2021-07-10 03:00
@KC-T 
@cleidigh 
and All.

This is my report.
I can't reproduce this in my environment.
Please see the screenshot.

Windows 10 Pro 21H1 64bit
Thunderbird 78.12.0 64bit (Releases Candidates)
PrintingTools NG 2.0.6

----

Normally, there is no message with an empty "To" field.
It seems to be a special kind of message.

１．What exactly is the message? Please let me know the details.
２．Please tell me the PrintingTools NG setting options that reproduce.
3．Also, can you attach a sample message here that reproduces the problem?
　[Steps]
　 A. Create a sample message with privacy information masked and edited.
　 B. Save the sample message as .eml.
　 C. zip or 7z to make a compressed file.
　 D. Attach it here.

**Empty "To" Field Test Message**
![Empty To Field Test Message](https://user-images.githubusercontent.com/80428201/125149705-7416b300-e175-11eb-8aef-5fbbb902bc96.png)

**Empty "To" Field Test Message Headers**
![Empty To Field Test Message Heders](https://user-images.githubusercontent.com/80428201/125149723-8bee3700-e175-11eb-8e9e-79fc91587df6.png)

**PrintingTools NG Options**
![PrintingTools NG Options](https://user-images.githubusercontent.com/80428201/125149730-9c061680-e175-11eb-853f-96d826844309.png)

**Comment by KC-T** [comment] 2021-07-10 04:31
Please see the attached zipped eml file, and image.
![Screen Shot 07-10-21 at 12 15 PM](https://user-images.githubusercontent.com/81372892/125151727-c0182680-e17a-11eb-954a-794814bdef90.PNG)
[20210709-Re_Border around the headers-160711.zip](https://github.com/cleidigh/printing-tools-ng/files/6794668/20210709-Re_Border.around.the.headers-160711.zip)

**Comment by kiki-ja** [comment] 2021-07-10 08:56
@KC-T 
@cleidigh 
and All.

Thank you for the sample message.

I was able to reproduce it in my environment.
Please see the screenshot.

**No [To:] [Cc:] [Bcc:] lines in the message headers**
![Sample Message](https://user-images.githubusercontent.com/80428201/125157728-80b3ff00-e1a7-11eb-8e90-4c8d56b7b788.png)

The problem occurs when there is no [To:] [Cc:] [Bcc:] lines in the message headerｓ.
It is not empty, it means that there are no [To:] [Cc:] [Bcc:] lines in the message headers.
If there is even one, a border around the headers will be displayed.

This is the first time I have seen a message without [To:] in the message headers.
Is it a special message from your own server?

I think there are two solutions.
1. Always use one of [To:], [Cc:], or [Bcc:] for send and receiveｄ messages. 
2. Ask the author, Mr. Christopher Leidigh, to take care of this for you.

That's all.

**Comment by KC-T** [comment] 2021-07-10 12:03
The email without stating the recipients was sent by another person intending to send to a group of undisclosed recipients. Thunderbird would have inserted "undisclosed recipients" there, but his email client did not.

**Comment by cleidigh** [comment] 2021-08-11 18:19
@KC-T 
@rroen
@RRoenn
@kiki-ja
@tidebre67 
@madvinegar


all

I am finally Pretty much  back to where I was
after a hospital 'Visit I got a 'rhinovirus

I am still Catching up
I will try to look at the issues

I would like some opinions:
I would like to get someone from the German
or Japanese user set to takeover the extension
My voice eventually will not allow to do the programming
Any thoughts ?
Christopher

**Comment by tidebre67** [comment] 2021-08-11 18:40
Christopher, in case of need what do you think whether John Bieling (Jobisoft)can take over ?  He is -as far as i know- a real expert with WebExtensions.  
Thomas

**Comment by RRoenn** [comment] 2021-08-11 19:12
Hello @cleidigh, i am very happy to hear from you after a long time and hope you feel better soon. 
I don't have the experience and skills to continue the add-on.

**Comment by cleidigh** [comment] 2021-08-11 19:56
all
unless there is some major issue I am going to make sure PT 'works with 91
if anyone know someone that might be interested in the extension
let me know
I know John well, we work together however John is now
officially employed by Thunderbird so he is not available
I also want to work put on getting something to help people take over extensions
Christopher

**Comment by cleidigh** [comment] 2021-08-12 00:03
FYI 
PT does not work with 9x
@cleidigh

**Comment by KC-T** [comment] 2021-08-12 00:56
@cleidigh 

I wish you well!

@KC-T

**Comment by cleidigh** [comment] 2022-03-28 17:37
This is similar to #111 
@KC-T gh is doing odd things showing this closed when it was not.
Closing and reopening 
@cleidigh

**Comment by cleidigh** [comment] 2022-03-28 17:55
@KC-T 
So i created an email with an empty to header and set the border option
and printing was normal.
is this still an issue in v2.1.0?
@cleidigh

**Comment by RRoenn** [comment] 2022-03-28 18:33
please try sample mail provided by @KC-T in https://github.com/cleidigh/printing-tools-ng/issues/79#issuecomment-877563467

https://github.com/cleidigh/printing-tools-ng/files/6794668/20210709-Re_Border.around.the.headers-160711.zip

I tried with an email not empty "To" field, but missing "To" field, can't reproduce the issue
**BUT** I can't print the sample mail provided by @KC-T ... I don't get a print preview

**Comment by cleidigh** [comment] 2022-03-28 19:52
@RRoenn 
Actually @KC-T 's email is not an empty To: field, but not present at all.
I get the same debug output as you. Yes that's the right output to capture.

I already have the date issue fix and this will be a similar fix.
@cleidigh

**Comment by cleidigh** [comment] 2022-03-30 20:45
@RRoenn 
@KC-T
b4 should take care of both missing date or to headers 
- #106 
- @cleidigh

**Comment by KC-T** [comment] 2022-03-31 18:09
Previously, if the To: field is empty. No border could be printed. -- b3 has this resolved.

**Comment by KC-T** [comment] 2022-03-31 18:12
Oh, I meant b4.

**Comment by cleidigh** [comment] 2022-04-02 20:23
Fixed issue with unicode detection 
@cleidigh

**Comment by cleidigh** [comment] 2022-04-08 00:11
Closed with b7

**Closed by cleidigh** 2022-04-08 00:11 UTC
