### ISSUE TITLE
Test reporting v2.0.5-b14

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#61] opened 2021-04-07 12:25 UTC
**latest xpi:**
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b14-tb.xpi

-----

_Originally posted by @cleidigh in https://github.com/cleidigh/printing-tools-ng/issues/53#issuecomment-813706893_

@KC-T 
@kiki-ja
@RRoenn

b6 should be ready to publish unless any issues posted
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b6-tb.xpi

**Comment by RRoenn** [comment] 2021-04-07 12:27
1. Overflowing table issue resolved. Thanks!
2. Long spacing in headers understood.
3. Truncated subject appearing in 2.0.5-b5 rectified in 2.0.5-b6.
4. Short (native) date or long localized date still give 12-hour format whether using UK or HK locale specifically defined to use 24-hour format in Windows 10.

K C

_Originally posted by @KC-T in https://github.com/cleidigh/printing-tools-ng/issues/53#issuecomment-813844115_

**Comment by RRoenn** [comment] 2021-04-07 12:27
@cleidigh 
Hello Christopher, 
Sorry for my lack of response over the Easter days.

my report with b6:
- my settings were retained
- **in the header of the settings dialog is the old version number 2.0.5-b3 displayed**
- **had to restart tb (multiple button in page preview)**
- background color checkbox and color are working
- rendering issue with the bottom border and the right border in page preview still exists, pdf and paper print outs are okay
- visibility and order of the message headers is working
- long list of adresses and long names of attachments are working
- the date format, that we are using, is fine. no checks on other options.

I hope that will help you.

_Originally posted by @RRoenn in https://github.com/cleidigh/printing-tools-ng/issues/53#issuecomment-813951173_

**Comment by RRoenn** [comment] 2021-04-07 12:27
@cleidigh 

Report about 2.0.5-b6.

1.Once the background color checkbox is turned on, it cannot be turn off.
This seems to be a problem only in the ja locale.


2.background color are working. This is good!


3.I have the same problem as Issue [Unable to save font selection.#47].
This seems to be a problem only with ja locale.


4.'null' appears at the bottom of the subject line when I turn off 'Align the headers'.
This seems to be a problem only with ja locale.
See screenshot.


5.'headers order' option is incorrect.
This seems to be a problem only with ja locale.
See screenshot.


I'm guessing that the problem with only ja locale is caused by the following
A. Added 'headers-ja.properties'.
B. Added code for 'headers-ja.properties' to 'printingtoolsng-pengine.js' and 'ptng-options.js'.
C. I'm having problems with the code added to them.
                                     
                                         
![Test Sample ja 01 205b6](https://user-images.githubusercontent.com/80428201/113731910-1cab1600-9734-11eb-85d0-eb0611348622.png)

![Test Sample en-US 01 205b6](https://user-images.githubusercontent.com/80428201/113732057-39474e00-9734-11eb-9aca-51c7b49645e2.png)

![Test Sample ja 02 205b6](https://user-images.githubusercontent.com/80428201/113732099-42381f80-9734-11eb-9ec1-b659b5edfabd.png)

![Test Sample en-US 02 205b6](https://user-images.githubusercontent.com/80428201/113732131-48c69700-9734-11eb-9723-cdfc025019c5.png)

_Originally posted by @kiki-ja in https://github.com/cleidigh/printing-tools-ng/issues/53#issuecomment-814195121_

**Comment by RRoenn** [comment] 2021-04-07 12:47
> 1.Once the background color checkbox is turned on, it cannot be turn off.
> This seems to be a problem only in the ja locale.

I also have this problem in the German version

> 3.I have the same problem as Issue [Unable to save font selection.#47].
> This seems to be a problem only with ja locale.

This is working fpr me in the tab Style and also in the tab "Adressbook printing"

> 4.'null' appears at the bottom of the subject line when I turn off 'Align the headers'.
> This seems to be a problem only with ja locale.

I get no 'null', but a a line break after the header 'subject' and the short subject text is at the next line. See screenshot from @kiki-ja

> 5.'headers order' option is incorrect.
> This seems to be a problem only with ja locale.
> See screenshot.

This is working for me.
I can't see a mistake at the screenshot @kiki-ja. Order is matching.

**Comment by kiki-ja** [comment] 2021-04-07 16:06
@cleidigh 
@RRoenn 

#61 Thank you for putting this together.
And thank you for the additional reports.


kiki-ja>    1.Once the background color checkbox is turned on, it cannot be turn off.
kiki-ja>    This seems to be a problem only in the ja locale.

RRoenn> I also have this problem in the German version

Thanks.
[about:config]
"extensions.printingtoolsng.headers.use_background_color"
I can't seem to switch between true and false, or save.


kiki-ja>    3.I have the same problem as Issue [Unable to save font selection.#47].
kiki-ja>    This seems to be a problem only with ja locale.

RRoenn> This is working for me in the tab 'Style' and also in the tab 'Adressbook printing'

Thanks.
In my case, the 'Style' tab is working fine, but the 'Addressbook printing' tab is not.
[about:config]
"extensions.printingtoolsng.addressbook.font_family"
I can't seem to change and save is not working.
In my case, it stays fixed to the 'Alef' font at the top of the font list.

It would be great if you could report back to #47 as well.


kiki-ja>    5.'headers order' option is incorrect.
kiki-ja>    This seems to be a problem only with ja locale.
kiki-ja>    See screenshot.

RRoenn> This is working for me.
RRoenn> I can't see a mistake at the screenshot @kiki-ja. Order is matching.

My screenshot shows the difference between the 'Headers order' settings and the Print Preview.

[en-US] locale is fine.
Headers order　--->　Print Preview
CC　　　　　　　　　　 --->　CC
BCC　　　　　　　　　--->　 BCC
Attachments　　--->　 Attachments

[ja] locale is invalid.
Headers order　--->　Print Preview
CC　　　　　　　　　　 --->　Attachments
BCC　　　　　　　　　--->　 BCC
Attachments　　--->　 CC

**Comment by cleidigh** [comment] 2021-04-07 18:45
@RRoenn 
@kiki-ja 
@KC-T
thanks guys, we will track the final testing here
I will try to work through these today
Christopher

**Comment by cleidigh** [comment] 2021-04-09 03:56
b7 with the following update
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b7-tb.xpi
- Use header background preference - all locales affected - reproduced/fixed
- unaligned headers layout/null fixed
- cc,bcc headers ordering fixed in Japanese locale
- force 24 hour time for Hong Kong
- time format debug
- localized width variation
 
I still cannot reproduce the issue with the font selection

**Comment by cleidigh** [comment] 2021-04-09 05:35
@KC-T
I was just looking and it does not appear that Thunderbird has the en-HK locale
I have tested en-GB and I see 24 hour time you should try
and also check the output
Christopher

**Comment by KC-T** [comment] 2021-04-09 07:24
@cleidigh 

I have finally identified the problem. We should change the language to English (United Kingdom) instead of the Date and Time Formatting of Thunderbird or Windows 10 in order to have 24-hour format:

![image](https://user-images.githubusercontent.com/81372892/114143955-5bfd8080-9947-11eb-88e7-49f1f5b2110b.png)

**Comment by RRoenn** [comment] 2021-04-09 08:02
my report with b7:

1. my settings were retained
2. in the header of the settings dialog is the old version number displayed -> okay after restart
3. multiple button in page preview -> okay after restart
4. check/uncheck background color -> worked after restart
5. rendering issue with the bottom border and the right border in page preview ... okay with 3 test mails
6. cc,bcc headers ordering
6a. visibility and order of the message headers is working
6b. **BUT:** different order and visibility, different intent spacing (see screenshots 1 and 2) I have only changed the order of the attachments.
6c. **there must be an select index error, if selected down; wrong item selected ... after some clicks, totally messed up, also visibility broken down**
7. long list of adresses and long names of attachments are working
8. _force 24 hour time for Hong Kong:_ the date format, that we are using, is fine. no checks on other options.
9. _Issue #47 [Unable to save font selection]:_ font type and size is saved
9a. tab 'Style'
9b. tab 'Adressbook printing'
10. _localized width variation_ **intent spacing, please see screenshots 2, is there a option to change?**
11. unaligned headers layout/null fixed -> **have a line wrap after the header 'subject' and the short subject text is at the next line**  (see screenshots 3)

Hope I collected all topics ...


@cleidigh did you get me mail?

![p1](https://user-images.githubusercontent.com/77779094/114146646-268d6e80-9918-11eb-80a3-10db1eaa302b.PNG)

![p2](https://user-images.githubusercontent.com/77779094/114146666-29885f00-9918-11eb-8f8a-914b248972ca.PNG)

![p3](https://user-images.githubusercontent.com/77779094/114148114-ba136f00-9919-11eb-92a6-0a6c825ff5c5.PNG)

**Comment by kiki-ja** [comment] 2021-04-09 12:14
[Thanks for the fix!]

1. I checked that the order of the Cc and Bcc headers has been fixed. (ja locale only issue).

2. Confirmed that show/hidden background color in header has been fixed.

3. Confirmed that 'null' in unaligned header has been fixed and disappeared.

4. No problem with date and time format in ja locale.
　

[Issues]

１．Unable to save font selection.#47
    'Addressbook printing' tab only.

２．unaligned headers layout.
    The subject(ja=件名) will be displayed below on a new line.
    See screenshot.

My System Requirements
OS: Windows 10 Pro 64bit 20H2
Thunderbird: 78.9.1 64bit ja version


![205b7-ja-locale](https://user-images.githubusercontent.com/80428201/114177955-fd042f80-9977-11eb-83aa-3ca9043857d0.png)

**Comment by kiki-ja** [comment] 2021-04-10 00:16
@cleidigh 

> I still cannot reproduce the issue with the font selection

I wrote a report on #47.
See also.

**Comment by cleidigh** [comment] 2021-04-10 01:23
@RRoenn 
I just found out I inserted a typo by dictation that messed up the spacing for the German locale.
I will explain tomorrow, a couple of adjustments
I also messed up the newline
@KC-T  your report is good, I was wondering if you were selecting the locale in TB
@kiki-ja your last info will help a lot, it's obviously an encoding issue
I have to find a Japanese font to test, suggestions welcome.

anyway, I am hoping tomorrow I can resolve these., time to get this out!
as always appreciate everyone's testing help!!
Christopher

**Comment by cleidigh** [comment] 2021-04-11 03:36
@kiki-ja 
I think I fixed the issue with fonts
unofficial test version
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b7b-tb.xpi
with my setup I could not absolutely verify however the fix source fairly obvious

**Comment by kiki-ja** [comment] 2021-04-11 13:09
@cleidigh 

[2.0.5-b8 report]

> １．Unable to save font selection.#47
> 'Addressbook printing' tab only.

> ２．unaligned headers layout.
> The subject(ja=件名) will be displayed below on a new line.
> See screenshot.

The previous two problems have been solved.
Thank you very much.

Please see the screenshot.


![205b8 test sample 01](https://user-images.githubusercontent.com/80428201/114305289-83547900-9b12-11eb-8fa5-2ac9701efb31.png)

**Comment by cleidigh** [comment] 2021-04-12 04:29
@tidebre67 
@RRoenn 
@kiki-ja 
@KC-T 
@madvinegar


okay all, b9 wraps a lot of things up with a little extra:
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b9-tb.xpi

- I made the first column width somewhat dynamic based on locale
- @R I realize this is not as configurable as your suggestion however
the table layout is? Complicated now uses fixed layout to control overflow.
I think this is a good compromise for now.
- @k I expand if attachments exist for the long word
- @ the selection printing should work for both preview and print

Finally, something for my friend @tidebre67 and all, border style:
you can now fully configure the CSS for the border
so for default: 
`border: 1px solid black`
for just a bottom, double, blue:
`border-bottom: 2px double blue`

notice this is really Pure CSS for the table element so you can be creative!
screenshots to follow
I am hoping no problem reports so I can clean and post.
Christopher

**Comment by cleidigh** [comment] 2021-04-12 04:52
German auto sizing
![image](https://user-images.githubusercontent.com/25272315/114341097-f36cfa00-9b26-11eb-88e9-3552ca35e572.png)

![image](https://user-images.githubusercontent.com/25272315/114341139-0ed80500-9b27-11eb-95d9-a0743e5d056f.png)

Japanese sizing
![image](https://user-images.githubusercontent.com/25272315/114341221-3f1fa380-9b27-11eb-8e4d-f53851440095.png)

![image](https://user-images.githubusercontent.com/25272315/114341250-4f378300-9b27-11eb-9b5d-861cf9877859.png)

styling
![image](https://user-images.githubusercontent.com/25272315/114342052-18fb0300-9b29-11eb-8898-4814dc8606a1.png)

![image](https://user-images.githubusercontent.com/25272315/114342146-53fd3680-9b29-11eb-90f5-19d7a7d41e46.png)

**Comment by kiki-ja** [comment] 2021-04-13 03:40
@cleidigh 

[Report 2.0.5-b9]

1. Pure CSS is a good idea.

2. When "aligin the headers = off", a small space appears after the subject.
    When "aligin the headers = on" it does not appear.

Please see the screenshot.
Can this be fixed?

![205-b9 Sample Print Preview 05](https://user-images.githubusercontent.com/80428201/114493235-26151080-9c55-11eb-9e6c-e534394c3ff7.png)

**Comment by cleidigh** [comment] 2021-04-14 04:28
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b10-tb.xpi
b10
- adjusted German layout
- adjusted first line gap
- added selection debug output

if anyone can help test selection  printing, @madvinegar still has a problem that I should have fixed, and I cannot reproduce.  specifically selection printing using file/print

For right now that's the only functional issue
Christopher

**Comment by kiki-ja** [comment] 2021-04-14 06:43
@cleidigh 

Test report 2.0.5b9 / 2.0.5b10

There is a problem with the 'Received:' header (ja=受信日時) being on a new line (line break) in both plain text and HTML text message display formats.

The following settings will reproduce the problem.
a. ja locale only
b. Multipart (Plain text & HTML text) messages only

[PrintingTools NG Option]
1. Aligin the headers = on
2. Style - Use fonts with a size in pixel of = off

[Multipart header]
Content-Type: multipart/alternative;

[Plain part header]
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

[HTML part header]
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

Please see the screenshot.
And I emailed a screenshot and a sample eml file to Christopher Leidigh.


**plain text - aligin the headers on - ja locale**
![plain text - aligin the headers on - ja locale](https://user-images.githubusercontent.com/80428201/114664810-34d3f400-9d37-11eb-9725-48be78eb0e5b.png)

**HTML text - aligin the headers on - ja locale**
![HTML - aligin the headers on - ja locale](https://user-images.githubusercontent.com/80428201/114664964-68af1980-9d37-11eb-8898-7255e29877b4.png)

**Style - Not Font Select - ja locale**
![Not Font Select - ja locale](https://user-images.githubusercontent.com/80428201/114664985-6e0c6400-9d37-11eb-82b1-e1d67715e478.png)

**Comment by RRoenn** [comment] 2021-04-14 09:28
@issue #62
printing plain selected text from plain text mails and also html mails without use print preview was successful
tested with tb 78.9.1-german (64bit) and v2.0.5-b10

@cleidigh 
your screenshots with autosizing are looking good
Have no time for full testing. Hopefully next week

**open bugs**
1. When "align the headers = off" still the line break after subject (Betreff) subject on new line
2. cc,bcc headers ordering, my issues 6.b and 6.c still exits, see https://github.com/cleidigh/printing-tools-ng/issues/61#issuecomment-816498651

>     6\. cc,bcc headers ordering
>         6.a visibility and order of the message headers is working
>         6.b **BUT:** different order and visibility, different intent spacing (see screenshots 1 and 2) I have only changed the order of the attachments.
>         6.c **there must be an select index error, if selected down; wrong item selected ... after some clicks, totally messed up, also set visibility broken down**

reproduce 6.c:
- select an item in the middle
- select down
- the item goes down, the highlight bar goes up

**Comment by cleidigh** [comment] 2021-04-16 01:29
b11 addresses the following:
@kiki-ja  - received  date line break
@RRoenn - 6a list up/down issues
no progress on the selection issue, however, @madvinegar may something unique
Christopher

**Comment by RRoenn** [comment] 2021-04-16 08:33
@cleidigh 

**solved:**
- _when "align the headers = off":_ no line break after subject (Betreff)
- 6.c: list up/down issue is fixed

open:
- 6.b different order -> different intent spacing (see screenshots 1 and 2) I have only changed the attachments from the last position to first; this only occurs, if the attachments are at the first position . Also at the second position, all is fine.
 
But that can be fixed with the next version.

attachments at the last position
![01_](https://user-images.githubusercontent.com/77779094/114996348-07a25580-9e9f-11eb-9a7d-07fb5bb863ea.PNG)

attachments at the first position
![02_](https://user-images.githubusercontent.com/77779094/114996440-20ab0680-9e9f-11eb-8a6d-5848f65d398b.PNG)

**Comment by RRoenn** [comment] 2021-04-16 08:50
Something is still buggy with the index. I just clicked a little bit around and after a lots of up and downs... Look at the screenshot, now From (Von) is missing.

At the beginning, if I selected the last element, I can't move down. That's okay. Later, the last element was after a down, at the top of the list.

![from](https://user-images.githubusercontent.com/77779094/114998456-42a58880-9ea1-11eb-83bf-0791e08e9907.PNG)

**Comment by kiki-ja** [comment] 2021-04-16 15:18
@cleidigh 

2.0.5-b11 Report.

The following two issues have been fixed in 2.0.5-b11.
Thank you very much!

'a small space appears after the Date'
https://github.com/cleidigh/printing-tools-ng/issues/61#issuecomment-818407963

'received date line break'
https://github.com/cleidigh/printing-tools-ng/issues/61#issuecomment-819271577

Please see the screenshot.

![205-b11 Test Sample](https://user-images.githubusercontent.com/80428201/115046443-694fd780-9f12-11eb-81f2-1da84bcc45e5.png)

**Comment by cleidigh** [comment] 2021-04-16 17:25
@RRoenn 
I will have to employ help, mouse movement by voice can be problematic
Oh well..

**Comment by cleidigh** [comment] 2021-04-17 02:03
@RRoenn 
b12 has some fixes for the list
I want to do more testing ,but I wanted people that have it Time to check 
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b12-tb.xpi

**Comment by kiki-ja** [comment] 2021-04-17 12:34
@cleidigh 

2.0.5-b12 Report.

A large blank appears when you make the 'attachments' the top of the list.

Steps to Reproduce
1.Headers order = 'Attachments' at the top
2.Miscellaneous = Aligin the headers = on

Please see the screenshot.


![205-b12 Header Test Sample en-US](https://user-images.githubusercontent.com/80428201/115113273-7af1b780-9fc4-11eb-97f4-fc923ba021fa.png)

**Comment by cleidigh** [comment] 2021-04-18 04:46
@kiki-ja 
fixed b13
I was hoping to wrap up, but I found a problem with received date

**Comment by cleidigh** [comment] 2021-04-18 05:24
all 
b14
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b14-tb.xpi
as far as I know this fixes all known issues

**Comment by kiki-ja** [comment] 2021-04-18 21:46
@cleidigh 

2.0.5-b13,b14 Report.

When the 'Attachments' is at the top of the headers list, there is no longer a large blank space.
"A large blank appears when i make the 'attachments' the top of the list."
https://github.com/cleidigh/printing-tools-ng/issues/61#issuecomment-821816031

Thanks for the fix.
Please see the screenshot.

![205-b14 Attachments Top Sample ja](https://user-images.githubusercontent.com/80428201/115161810-a8308980-a0da-11eb-81f6-bbbafaddc73f.png)


Additional Information.
2.0.5-b14 is also working with Thunderbird 88.0beta3.

**Comment by cleidigh** [comment] 2021-04-19 05:03
@kiki-ja 
excellent!
starting cleanup

**Comment by RRoenn** [comment] 2021-04-19 08:32
@cleidigh 
All worked for me.

I couldn't break the item list, I think you catched the bug ;-)
(https://github.com/cleidigh/printing-tools-ng/issues/61#issuecomment-821025928)

Also when the 'Attachments' is at the top of the headers list, there is no longer a large blank space.
my 6.b different order -> different intent spacing (https://github.com/cleidigh/printing-tools-ng/issues/61#issuecomment-821015954)

Thank you very much

**Comment by cleidigh** [comment] 2021-04-22 04:02
@RRoenn
@kiki-ja
@tidebre67 
@KC-T 
@madvinegar

v2.0.5 has been posted to the Q
a really huge thank you to everyone, this took a little too long ,but I am getting slower unfortunately, 

note I made Max compatibility 87.0 four which was the highest allowed currently
I am sure there are issues somewhere
cheers
Christopher

**Comment by KC-T** [comment] 2021-04-22 04:45
@cleidigh 

Thank you, Christopher!

K C

**Comment by cleidigh** [comment] 2021-04-22 20:14
it's out!

**Closed by cleidigh** 2021-04-22 20:14 UTC
