### ISSUE TITLE
Add auto PDF naming as in IETNG

### ISSUE THREAD

**Issue by JF1313** [cleidigh/printing-tools-ng#151] opened 2022-12-05 12:24 UTC
Thanks for the plug-in.

Is there a way to:

1. Automatically save an email as a PDF without the print dialog box?
2. Add the current date in YYYY MM DD SUBJECT as the name?

Thanks.

Jeffrey

**Comment by JF1313** [comment] 2022-12-06 11:24
Thanks for the update and as someone who uses ImportExportTools NG I'm grateful for the ability to save a PDF without a dialog box. 

Here's something to think about. Since ImportExportTools NG already prints without a dialog box, it would be great if ImportExportTools could be triggered through a filter. A few days back I reached out to the creator of FiltaQuilla to find out if this could be added. Perhaps there's a way to save you time through collaboration.

Either way, thank you for your great work!

**Comment by cleidigh** [comment] 2022-12-06 15:08
@JF1313 
Yes, Axel and I spoke about this yesterday.
We will keep you posted,. 
Thanks 
@cleidigh

**Comment by cleidigh** [comment] 2022-12-08 03:01
@JF1313 
While I do not know if I can get this in the ui for the next release , I think I can enable it with some hidden prefs.
It makes sense to do this in ptng as it already has the external interface
I will post when I have something.
@cleidigh

**Comment by JF1313** [comment] 2022-12-08 12:19
Chris, it would be *great* if this can be done! Perhaps you can keep me updated as you move through the process. I appreciate your continued help and support.

**Comment by cleidigh** [comment] 2022-12-15 22:24
@JF1313 
I am posting another test version of the page options. After I will check the silent printing with FiltaQuila and begin a version with a first pass on the default pdf output directory. Not that it matters to you, but I have to decide if I will do it on beta or test.

Regardless, here are my current thoughts...
- add three new prefs
- enable default pdf output directory 
- pdf output directory 
- custom output filename - token system as used by IETNG 
- custom date format from IETNG 
- if not enabled prompt for directory else use default directory 
- may not get in ui yet

Let me know if I am missing something.
@cleidigh

**Comment by JF1313** [comment] 2022-12-16 10:15
@cleidigh
Thank you for the update and for your time and effort to take your plug-in to an entirely new level.

Your suggestions and the three new prefs look great. Happy to test directly for you or though beta.

How I think about the enhancement is taking IETNG and as it is and building it into FiltaQuila.

Thanks.

Jeffrey

**Comment by JF1313** [comment] 2022-12-16 17:10
@cleidigh
One other thought. There are times when the Subject line of an e-mail will have illegal Windows characters (non-Latin) such as emojis or accents. It would be *terrific* if both IETNG and IETNG within FIltaQuila would ignore the illegal Windows characters.

Thanks.

Jeffrey

**Comment by cleidigh** [comment] 2022-12-16 17:28
@JF1313 
IETNG does a bunch of sanitizing of the filenames. I have no idea about emojis, I will have to check onthat...Good point.
@cleidigh

**Comment by cleidigh** [comment] 2022-12-20 02:16
@JF1313 
Comments:
Accents are not illegal , <>:/\ etc... are illegal, utf-8 chars also legal

I think I need subject and filename limits as in IETNG

For a silent print with no dir, must do popup err 
@cleidigh

**Comment by JF1313** [comment] 2022-12-20 11:50
@cleidigh
Thanks for the clarification. My terminology was not correct. 

Is it possible to have accents ignored when saving to PDF?

**Comment by cleidigh** [comment] 2022-12-21 17:53
@JF1313 
So just for my understanding, why exclude these characters? You also spoke about emojis. Are you trying to only have ascii characters?
I cannot substitute an accented A for an A because there are hundreds of possibilities with utf-8.
I could substitute with an underscore, but that could be ugly.
@cleidigh

**Comment by JF1313** [comment] 2022-12-21 19:14
@cleidigh
We find that accents, emoji's and other "funny" characters aren't copied properly when we're performing backups over FTP. Some of our systems are legacy systems and can't handle the characters. The end result are constant errors. We end up manually going into the system to find the file and rename it with "standard" characters. 

Anything that can be done to help minimize these kinds of errors is appreciated.

Thanks.

Jeffrey

**Comment by cleidigh** [comment] 2022-12-21 19:58
@JF1313 
That makes sense, but would replacing any non ascii with an underscore do the trick? Or do you have something else in mind.
Btw I have the base infrastructure in place and will have a first pass soon.
@cleidigh

**Comment by JF1313** [comment] 2022-12-21 20:11
@cleidigh
Thanks for your continued attention to details. An underscore is great. Looking forward to your first pass.

**Comment by cleidigh** [comment] 2022-12-21 22:29
@JF1313 
I was just looking at your date format and you referred to it as the "current date", do really mean the date of pdf creation or the date of the message?
I only have the later now.
@cleidigh

**Comment by cleidigh** [comment] 2022-12-21 23:51
@JF1313 


Allright, first beta. 

Not all the error handling needed etc.

Silent printing to any printer with pdf in name.
Need to setup preferences below.
Format is hard coded as 
{custom-date} {subject}

Otherw just the subject.
I don't have the token system yet.
The custom date (of message) is configurable as per IETNG.

Filenames are sanitized with underscores for invalid characters.
Duplicate files have a -XXX suffix added.

Tested with TB 91 and FiltaQuila 3.4, could not get latest 102 FiltaQuila to work. I will check with Axel...

Preferences :

extensions.printingtoolsng.pdf.enable_pdf_output_dir = true
extensions.printingtoolsng.pdf.output_dir <path to folder>
extensions.printingtoolsng.pdf.custom_filename_format = "{custom-date} {subject}"
extensions.printingtoolsng.pdf.custom_date_format = "%Y %m %d"

You have to enter the full pref name the first time, defaults don't show up.

We can discuss the potential sanitizing later, it's tricky...

@cleidigh 

https://github.com/cleidigh/printing-tools-ng/blob/v2.2.0/xpi/printing-tools-ng-2.2.0-b1-tb.xpi

**Comment by cleidigh** [comment] 2022-12-22 03:51
@JF1313 
Clarifications just in case...
I quoted strings, do not include
path should be native format
C:\Documents
eg for windows
Dont foget filename format has to be exact, with space for now
When i say invalid characters replaced i only mean invalid filename chars.
I will look at substitutions next.

Reminder to answer date and other questions above...
@cleidigh

**Comment by JF1313** [comment] 2022-12-22 11:33
@cleidigh
Thanks for the follow-up, I was traveling and catching up on emails.

In answer to your earlier question the date is what you have with the date of the email and/or conversion of the file.

I will download and try the extension.

THANK YOU.

Jeffrey

**Comment by JF1313** [comment] 2022-12-22 11:36
@cleidigh when installing the beta, Thunderbird says it can't install because the file appears to be corrupt. I'm on version 102.6.0 64-bit. Please let me know if there's something for me to do for the plug-in to be accepted.

**Comment by cleidigh** [comment] 2022-12-22 19:30
@JF1313 
I Don't know why. But this seems to happen frequently. Try downloading again and/or use another browser.
You will not be able to use 102 as I couldn't get FiltaQuila to work with PTNG using the latest FiltaQuila. Have you been able to?
I used TB 91 and FiltaQuila 3.4

@cleidigh

**Comment by cleidigh** [comment] 2022-12-22 20:22
@JF1313 
Actually I got TB 102, FiltaQuila 3.61 and PTNG b1 working...
@cleidigh

**Comment by cleidigh** [comment] 2022-12-22 23:47
@JF1313 
Ask and we(me) shall deliver 🥇 
I found a great little method that does a latinize on a string. Instead of removing accents and non latin characters it replaces  them with latin characters.
I also have emoji removal, but I am still working on that.
Check it out and see if anything escapes it.
I think this will be even better than expected.
@cleidigh 

https://github.com/cleidigh/printing-tools-ng/blob/v2.2.0/xpi/printing-tools-ng-2.2.0-b2-tb.xpi

**Comment by JF1313** [comment] 2022-12-23 12:58
@cleidigh
Wow, thanks for the great news and the progress you're making!! 🙏🙏🙏👍👍

I've downloaded and installed 2.20 b2 on Thunderbird 102.6.1 and Filtaquila 3.6.1

Below is a screenshot of the FIltaQuilla settings. At the risk of asking a newbie question, when the filter runs how/where do I select the output folder for the PDF?

![Options](https://user-images.githubusercontent.com/27140836/209339723-5243eae1-4370-4bf5-a546-0a65edb19426.png)

**Comment by cleidigh** [comment] 2022-12-23 17:06
@JF1313 
I like your appreciation emojis, we won't filter those!
Your FiltaQuila settings are correct. All other settings are in PTNG, however, as I stated above the settings need to be done with the advanced preferences editor. Look above at the four preferences you need to set.
For each pref copy the full pref name into the search bar, then it will allow you to set the value. I listed them above.
Let me know, I will be online until 6pm EST
@cleidigh

**Comment by JF1313** [comment] 2022-12-24 11:19
@cleidigh
You had me smiling with your comments and not filtering the emojis in my last comment :-)

My travels have my replies sporadic and thanks for your patience.

At the risk of another newbie question, in PrintingTools NG, where do I find the advanced preference editor?

I

**Comment by cleidigh** [comment] 2022-12-24 22:19
@JF1313 
Levity is a most important currency, especially these days!
My apologies assuming certain things.
Also you are traveling so (and it is the holidays after all) don't worry about quick replies, I have tons to do so I am moving ahead to add the full token system.

On the preferences : 

As I mentioned earlier I may not get the new options into the UI for several reasons including the fact that many other changes are also happening. This means we will have to set these new preferences in the advanced config editor. This is the global preferences system similar to the windows registry. I will include some screen shots. Each preference is a name value pair. For extensions the name might look like : 

extensions.printingtoolsng.pdf.enable_pdf_output_dir

This is in fact the first new pref we need to set to true to enable the silent save directory. Then we have the others including directory, filename and date formats. 

Here is an article on the config editor.
https://support.mozilla.org/en-US/kb/config-editor

For our new we actually need to paste each name into the search bar and then set the value. It doesn't matter which order you enter them.
Here are the preferences again. Note that you will have to enter a directory for your system, the others I have given you the values, however you can change the date format if you wish. The filename format is fixed right now.

 Preferences :

extensions.printingtoolsng.pdf.enable_pdf_output_dir = true
extensions.printingtoolsng.pdf.output_dir <path to folder>
extensions.printingtoolsng.pdf.custom_filename_format = "{custom-date} {subject}"
extensions.printingtoolsng.pdf.custom_date_format = "%Y %m %d"

Don't enter the quotes on the strings and enter the filename format with the space between the date and subject tokens.
Once these are set, set your printer to a pdf printer and then FiltaQuila should trigger the silent print to your configured directory.
@cleidigh

**Comment by JF1313** [comment] 2022-12-25 12:15
@cleidigh
Thanks for your patience and directions. 

If you celebrate Christmas, Merry Christmas, and if not, Happy Holidays.

I have entered the above preferences and removed the quotes. I've included a screenshot. I entered the preferences without the quotes.

At the moment, there is no PDF file. If you can let me know what adjustments I need I'd appreciate it.

Thanks.

Jeffrey
![Preferences](https://user-images.githubusercontent.com/27140836/209467513-4131660a-9522-419f-ab7f-468ed0ef9d4b.png)

**Comment by cleidigh** [comment] 2022-12-25 16:09
@JF1313 
A very Merry Christmas to you if you celebrate as well, otherwise Happy Holidays!!

Simple answer is you combined the name and value including the = sign, I should have been clearer.  

Easy fix.  At the top of your filtered prefs you see the light grey entry with the name ...pdf.custom_date_format
Notice no value on right.  Click the edit pencil and enter
%Y %m %d

no quotes or equals
Now just below you can delete the incorrect combined name entry
Now do the same for the custom filename format and directory entries
set the enable to true
I can send a screenshot when i am on my main system.
Christopher

**Comment by JF1313** [comment] 2022-12-25 16:34
@cleidigh
Thank you for your Christmas and Holiday greetings!

Ah, I now understand what was meant in your original message and I learned something new about entering/modifying advanced preferences. Changes are done and everything is working 👍🙏✔✨🎈

I will continue to test and monitor.

Please let me know how else I can help with the testing.

Thanks.

Jeffrey

**Comment by cleidigh** [comment] 2022-12-25 20:16
@JF1313 
Great, did you try some emails with accents and emojis?
@cleidigh

**Comment by JF1313** [comment] 2022-12-26 11:31
@cleidigh
Once again, thanks for your continued help and support :-)

Great news!

Emojis are removed as well as letters with accents which are replaced with regular letters. Nicely done!

I have a question and suggestion and openly, the plug-in as is is great and you've done a terrific job. Here's the "icing on the cake:"

1.  I've noticed on the PDF that the ending has "from MM_DD_YYYY.PDF". Is there a way to either remove this or have it as an option? Since the start of the file has the date already, the "from MM_DD_YYYY.PDF" is not necessary.

2. Here's the question and it may be a reach. Is it possible in either the From: or Subject to remove an apostrophe? An example is: Jeffrey's. I've come to learn that the apostrophe isn't recognized by some legacy FTP systems creates issues when copyingthe files.
3. 
Thanks.

Jeffrey

**Comment by cleidigh** [comment] 2022-12-26 18:17
@JF1313 
I am not sure about #1. You mention "from" and a date. So for an email with a subject : 
Test Sub
Using our current settings the resulting file should be: 
2022 12 26 Test Sub.pdf

There should be no from or second date.
I think I am missing something?

On # 2 I will have to think about that.
@cleidigh

**Comment by JF1313** [comment] 2022-12-27 15:32
@cleidigh
The latest emails do not display the same "from" at the end of the email. It may have been the email themselves that had this information. Let's take this issue off the table.

Thanks for thinking through suggest #2.

Jeffrey

**Comment by JF1313** [comment] 2022-12-28 15:16
@cleidigh

I continue to enjoy the enhancements you've made to the plugin. They heartfeld. Thank you for this .

I find that there are some emails where it is a generic subject line making it difficult to sort the PDF. As you think about the foggian going forward, I'm wondering if there is a way to add the friendly name from the email address to help identify the sender. As an example, if the email was support@gmail.com and the friendly name was Gmail, the Gmail name would appear in the PDF file name

Thanks. 

Jeffrey

**Comment by cleidigh** [comment] 2022-12-28 22:57
@JF1313 
So I have the full token system in. You can now define the filename format as defined in IETNG. Note: I had the custom date format token wrong.
It should be ${date_custom}

I have several preferences to control filtering, you will have to set these as before. I aso added a character filter, set the string with any characters you want removed. No spaces or separators.



extensions.printingtoolsng.pdf.filename.prefix = <string>
extensions.printingtoolsng.pdf.filename.suffix = <string>
extensions.printingtoolsng.pdf.filename.filter_characters = <string>
extensions.printingtoolsng.pdf.filename.latinize = true/false
extensions.printingtoolsng.pdf.filename.filter_emojis_and_symbols = true/false

You can use the ${sender_email}
to get support@gmail.com into the name.
Extracting anything else would be too specific and difficult.

https://github.com/cleidigh/printing-tools-ng/blob/v2.2.0/xpi/printing-tools-ng-2.2.0-b3-tb.xpi
@cleidigh

**Comment by JF1313** [comment] 2022-12-29 13:36
@cleidigh
Wow, you've made a lot of *great* enhancements to the plug-in. Thank you :-)

Please confirm what happens when "True" is set for the latinize preference.

Also, please confirm that a value of "True for emojis removes emojis and symbols.

Looking forward to testing out the latest beta.

Thanks.

Jeffrey

**Comment by JF1313** [comment] 2022-12-29 13:43
@cleidigh
I ran a quiick test. The name of the PDF now appears as {custom-date} {subject}-001.pdf

I've enclosed a screenshot of advanced preferences. Plesae let me know now to have the filename back to the intended format.

THanks.

Jeffrey

![Preferences](https://user-images.githubusercontent.com/27140836/209962157-c2a9e205-25e4-4cbf-960f-902f54357c09.png)

**Comment by cleidigh** [comment] 2022-12-29 20:44
@JF1313 
Couple setup points.
The token system is the same as IETNG so please refer to the help there which has all the token definitions.
My initial, hard coded filename format was wrong. First, all tokens are : 
${token name}

Also matching IETNG, the custom date is : 
${date_custom}

So yours should be: 
${date_custom} ${subject}

I have added the ${suffix} and ${prefix} tokens, however, these are meant to be static strings. There is no token substitution within them so your suffix preference would be wrong. They can actually appear anywhere in the filename format.  If you want the sender email the you place that in the filename format:
{date_custom} ${subject} ${sender_email}

Just like IETNG you can arrange whatever tokens you like with extra characters if you like, separators, etc.

The latinize preference turns on or off the transliterator for things like accents you asked for. There are several hundred, I can send you the table if you are interested.  The emojis and symbol filter turns the removal of emojis and unicode symbols.  The character filter is what you wanted to filter out apostrophes or any other characters. Just put one or more characters in the string, no separators quotes or anything else.  So whatever your ftp server doesn't like that the other filters or latinization does not take care of you can use the character filter.

@cleidigh

**Comment by JF1313** [comment] 2022-12-30 14:29
@cleidigh
Thanks for the detailed explanation above and the entries for the file name.

The updated preferences now remove the emoji's and any additional characters that I add which is a nice touch. Thank you!

Speaking of preferences, at the risk of asking a newbie question (many of them) I'm still not able to have the actual date show up in the file name. The advanced preference for the custom date is set to %Y %m %d which yields {date_custom} in the file name itself. 

Your insights as to how I can have the date show up in the file name is appreciated.

Thanks.

Jeffrey

**Comment by cleidigh** [comment] 2022-12-30 16:52
You need the token as
```${date_custom}```
It looks like you are missing the $ in front of the open brace?
@cleidigh

**Comment by JF1313** [comment] 2022-12-30 20:52
@cleidigh

Thanks for the confirmation. The date is now appearing :-)

**Comment by cleidigh** [comment] 2022-12-30 21:05
Great, so it sounds complete.
I am cleaning up and returning to the page options feature for the next release.
Happy New Year!
@cleidigh

**Comment by JF1313** [comment] 2022-12-30 21:08
@cleidigh

Thanks for the quick reply and the update. Looking forward to your continued progress as you haven't done so much in a short period of time. The added functionality is fantastic .

In the interim, wishing you a new year that has you last, and great health, sweet success, and all the good things of life I saw for real

Jeffrey

**Comment by cleidigh** [comment] 2022-12-31 21:40
Jeffrey 
All the same to you!
BTW reviews are always appreciated 👍 
@cleidigh

**Comment by JF1313** [comment] 2022-12-31 21:47
@cleidigh
One more Nessie question for you.
Where/how do I leave a review?

**Comment by cleidigh** [comment] 2022-12-31 21:55
@JF1313 
On the Thunderbird addon homepage.
https://addons.thunderbird.net/EN-us/thunderbird/addon/printingtools-ng/?src=dp-dl-othersby
@cleidigh

**Comment by JF1313** [comment] 2022-12-31 22:11
@cleidigh
Happy to share a review and contribute. Thanks you again for your continued help and support with the plug-ins.

**Comment by cleidigh** [comment] 2022-12-31 22:34
Jeffrey 
Very nice review.
And thanks for your overly gracious contribution!
I think many users will benefit from this feature and thank you for working through the issues with me.
Cheers 
Christopher

**Comment by JF1313** [comment] 2023-01-04 11:37
@cleidigh
One other question.

In ImportExportTools NG I noticed that when saving a file there is the option to include "Name (Sender)"

I was wondering if the same option could be offered into the PrintTools NG

Thanks.

Jeffrey

**Comment by cleidigh** [comment] 2023-01-04 17:25
@JF1313 
Yes ptng tokens are the same as IETNG. See help:

<img width="960" alt="2023-01-04-12-19-31 " src="https://user-images.githubusercontent.com/25272315/210613461-ecc9f7b6-54c2-40c1-aed4-637e422a5313.png">

Note ${index} is broken due to some api issue.
@cleidigh

**Comment by JF1313** [comment] 2023-01-05 12:16
@cleidigh
Thanks, I've updated the settings and it's working.

Much appreciated.

**Comment by cleidigh** [comment] 2023-01-05 18:13
@JF1313 
Great, i am working on integration now so next beta will be a bit.
@cleidigh

**Comment by JF1313** [comment] 2023-01-05 19:08
@cleidigh
Thanks for the update. Looking forward to the next beta when ready.

**Comment by cleidigh** [comment] 2023-01-12 02:22
@JF1313 
@kiki-ja 
Ok, lots of New Year activity!
Everything is merged.
Big beta...
- Dark mode
- Major UI overhaul 
- Page options
- PDF auto naming with tokens (multiple selection and external)

I am sure there are edge conditions,but that's next

@JF1313 
You will have to reenter the custom date as the pref changed

https://github.com/cleidigh/printing-tools-ng/blob/v2.2.0/xpi/printing-tools-ng-2.2.0-b5-tb.xpi

@cleidigh

**Comment by JF1313** [comment] 2023-01-12 21:25
@cleidigh
Wow, you've been busy!

I've installed the latest beta and really like what I'm seeing. Noted on the custom date and re-entered in the interface itself. I'll test out and reach out with questions and/or comments.

That said, a note of thanks and gratitude @cleidigh for the terrific enhancements!

Thanks.

Jeffrey

**Comment by cleidigh** [comment] 2023-01-12 22:12
@JF1313 
Yup a lot of work!
I have one bug I realized last night.
The date format pref is incorrect for printing, the old pref gets used not the one set in the ui. So your old pref will be used when you actually print.  I had an unusable eye gaze for my computer today so may have to wait until tomorrow for an update.
I have to also describe this new feature for non external printing.
@cleidigh

**Comment by kiki-ja** [comment] 2023-01-13 10:51
@cleidigh 

>Everything is merged.
>Big beta...
>
>     * Dark mode
> 
>     * Major UI overhaul
> 
>     * Page options
> 
>     * PDF auto naming with tokens (multiple selection and external)

Thanks for the merge work.
Very NICE and GREAT!

Please let me know when the beta is ready as I would like to localize it before release.

@kiki-ja

**Comment by JF1313** [comment] 2023-01-13 12:17
@cleidigh

Thanks for the update. Here's to you feeling better with a full recovery!!

**Comment by cleidigh** [comment] 2023-01-13 14:23
@kiki-ja 
Will do. Still probably need to finalize strings and add help.
@JF1313 
It is my eye gaze system for my ALS, it was out of control yesterday for half the day then miraculously recovered???
Anyway I will post the bug fix today. Have to also note other bugs.
@cleidigh

**Comment by cleidigh** [comment] 2023-01-13 18:55
@JF1313 
@kiki-ja 
Here is the hotfix for the custom date, it will use the ui custom date everywhere now. At this point we should be able to test everything.

https://github.com/cleidigh/printing-tools-ng/blob/v2.2.0/xpi/printing-tools-ng-2.2.0-b6-tb.xpi
@cleidigh

**Comment by JF1313** [comment] 2023-01-13 20:33
@cleidigh
Glad to hear you back on track!!

**Comment by cleidigh** [comment] 2023-01-16 22:05
@kiki-ja 
@JF1313 
I have disabled copies for pdf drivers, open folder dialog when output dir not enabled. Also cleaned ui, @kiki-ja merged your edits (changed some) and edited help.
I think we are down to test, translations and cleanup.
@JF1313 Any more testing of the pdf options would be great.
@kiki-ja if you wish you could catalog what new translation items we need then I can add the placeholders.

https://github.com/cleidigh/printing-tools-ng/blob/v2.2.0/xpi/printing-tools-ng-2.2.0-b6-tb.xpi
@cleidigh

**Comment by kiki-ja** [comment] 2023-01-17 14:24
@cleidigh 

I installed PTNG 2.2.0-b7.
This is correct, right?

>@kiki-ja merged your edits (changed some) and edited help.

Confirmed. Thank you.

>@kiki-ja if you wish you could catalog what new translation items we need then I can add the placeholders.

I am picking up new translation items.
Is cataloging simply listing them?
Text file? Format?

@kiki-ja

**Comment by cleidigh** [comment] 2023-01-24 00:20
@JF1313 
b13 is out and the main ui translated.
- #157 
- @cleidigh

**Comment by JF1313** [comment] 2023-01-24 13:01
@cleidigh

Great news! I will download and test.

**Comment by cleidigh** [comment] 2023-01-24 20:00
@JF1313 
FYI while the translations are in I have to complete the localized css. Other than en and ja the input fields are wrong.
fixes soon...
@cleidigh

**Comment by JF1313** [comment] 2023-01-24 20:31
Thanks, @cleidigh.

Am I correct in understanding that as long as I am in EN I won't have any issues?

**Comment by cleidigh** [comment] 2023-01-24 20:41
@JF1313 
Yes while I am stll doing small tweaks the en layout is very close. For other locales css widths are not set yet.
@cleidigh

**Comment by JF1313** [comment] 2023-01-25 11:31
@cleidigh
Thanks, Christopher 🙏

**Comment by dstark** [comment] 2023-03-14 16:47
Just wanted to chime in to say thank you SO much for raising this suggestion (@JF1313) and building out the solution for it (@cleidigh). The latest beta works fabulously for me. Really appreciate it!

Just so I'm sure I understand moving forward—Will I need to reinstall the addon from the Thunderbird repository once it's pushed out? Or will it automatically pull in updates from there?

**Comment by cleidigh** [comment] 2023-03-14 17:51
@dstark 
Ahh, a user before we release, love it!
Couple notes I had a regression bug from b28 to b32pre2, just fixed last night with pre3. Doing pdf auto save on same message had a cache issue. Also fixed initial prefs for filename and custom date. Also taking care of win filename max len for win.
Very glad you like it, actually meant to port this over a while ago... 

To your question, I don't trust atn when dealing with beta. I am hoping for release to the review Q in a couple of days. Final testing now.
I will let you know.
Reviews always welcome  %-)
Cheers 
@cleidigh

**Comment by cleidigh** [comment] 2023-03-14 23:35
@JF1313 
@kiki-ja 
@RRoenn 
@tidebre67
Never enough testing!
Found 3 bugs with pdf output.
- maxfile length truncation 
- filename format and custom date defaults missing 
- Linux file picker api difference caused exception 

Have fixed all, need more Linux testing tomorrow.
@cleidigh

**Closed** 2023-03-17 19:01 UTC
Labels: enhancement, PDF
