### ISSUE TITLE
Add Multiple text selection for PTNG  printing

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#99] opened 2022-03-07 08:29 UTC
@cleidigh 

PrintingTools NG 2.1.0
Thunderbird 91.7.0 64bit
Windows 10 Pro 21H2 64bit

I would like to be able to select multiple texts in PrintingTools NG and print them.

Thunderbird can select multiple texts and print them.
However, PrintingTools NG printing can only print a single text.
Please see the screenshot.

![multiselect tetx result 02](https://user-images.githubusercontent.com/80428201/156995110-ea5b6936-6435-46c1-af75-ea46d072b439.png)

@kiki-ja

**Comment by cleidigh** [comment] 2022-03-07 17:59
@kiki-ja 
I changed the title to reflect this is a new feature.
@querixg also desires this.
As I stated before we should be able to do this, just don't know what surprises we will have  ;-)
@cleidigh

**Comment by kiki-ja** [comment] 2022-03-08 07:29
@cleidigh

It is a function that is possible with Thunderbird's normal printing.
So I would like to have the same functionality as normal printing.

>@querixg also desires this.

Since #80 is closed, I've created a new issue.

>As I stated before we should be able to do this, just don't know what surprises we will have ;-)

Best regards. Thank you.
@kiki-ja

**Comment by cleidigh** [comment] 2022-03-09 00:33
@querig
@kiki-ja 
So here is a rough fist pass.
It will only work with text now.
I have it doing one block per selection with a line breaks 
this is different than Thunderbird, but I think it makes sense as if one selects
multiple paragraphs they should be separated.
Of course your opinions requested.

I finally found a poor way to select with the eye gaze, however, it is limited so your testing will be interesting.

change zip to xpi

[printing-tools-ng-2.1.0-dbg1-tb.zip](https://github.com/cleidigh/printing-tools-ng/files/8210694/printing-tools-ng-2.1.0-dbg1-tb.zip)

@cleidigh

**Comment by RRoenn** [comment] 2022-03-09 08:24
Hello @cleidigh 

I prefer your solution with a line break between multiple paragraphs
**100%**

Unfortunately I don't have time to test it

**Comment by cleidigh** [comment] 2022-03-09 22:05
@kiki-ja 
@querixg
This pass handles html
but does weird things if one selects part of a table 
really stumped on that.

@cleidigh 

[printing-tools-ng-2.1.0-dbg2-tb.zip](https://github.com/cleidigh/printing-tools-ng/files/8218465/printing-tools-ng-2.1.0-dbg2-tb.zip)

**Comment by kiki-ja** [comment] 2022-03-10 13:10
@cleidigh
@querixg
All

PrintingTools NG 2.1.0 dbg2
Thunderbird 91.7.0 64bit
Windows 10 Pro 21H2 64bit

Here are my test results.
Multiple texts can be selected for printing.
Line break position, layout, "..." and other issues.

![Multi select text sample 03](https://user-images.githubusercontent.com/80428201/157667861-10ca2732-75a9-4345-a895-0aba00fee7b8.png)

[console-export-2022-3-10_21-30-22.txt](https://github.com/cleidigh/printing-tools-ng/files/8223580/console-export-2022-3-10_21-30-22.txt)

Please feel free to use the eml files created for testing purposes.
[Sample message for test.zip](https://github.com/cleidigh/printing-tools-ng/files/8223585/Sample.message.for.test.zip)

@kiki-ja

**Comment by RRoenn** [comment] 2022-03-10 13:36
[printing-tools-ng-2.1.0-dbg2-tb.zip]
Thunderbird 91.7.0 (64bit) - german
Windows 10 Pro 21H2 64bit

fresh installation, new profil

I can't print multiple text selections.
print preview shows the complete mail 

I can open eml from desktop and print with PT ng *GREAT*

**Comment by RRoenn** [comment] 2022-03-10 13:43
![test1](https://user-images.githubusercontent.com/77779094/157674184-4663c336-3c1c-42c8-80cc-4a361910e412.PNG)

**Comment by RRoenn** [comment] 2022-03-10 14:14
![test12](https://user-images.githubusercontent.com/77779094/157679812-e97e7eb7-1e90-4e33-a0b4-4d3af6b01793.PNG)
![test13](https://user-images.githubusercontent.com/77779094/157679822-2e92c18a-3ed5-4073-8779-c8682d479c25.PNG)

**Comment by cleidigh** [comment] 2022-03-11 01:42
All

This is a huge can of worms!

I have figured out how tb does this and its buried and complex, basically something I cannot recreate, but I have some ways to utilize the multiple selection path.
Right now there are consequences that have to be overcome.

I will investigate...
@cleidigh

**Comment by cleidigh** [comment] 2022-03-13 23:27
All
dbg3 has a different approach so whatever you observed before is moot.
This version uses the standard internal selection path which unique to Firefox and Thunderbird allows multiple selections including in tables.

Because I use the tb selection handling I cannot manually add line breaks, everything is controlled by Thunderbird.
I was hoping to be able to do those for pure text,but my tricks so far failed.

I need confirmation that this approach works before I attempt anything else.

[printing-tools-ng-2.1.0-dbg3-tb.zip](https://github.com/cleidigh/printing-tools-ng/files/8240809/printing-tools-ng-2.1.0-dbg3-tb.zip)

@cleidigh

**Comment by querixg** [comment] 2022-03-14 08:33
It works! Many thanks!

**Comment by querixg** [comment] 2022-03-16 17:14
@cleidigh
1. Minor problem: If one selects some part of the body, chooses Print NG, cancels the preview, cancels the selection by clicking somewhere else in the body, and chooses Print NG again, then in the preview (and the printout) the body will be empty. I.e. PTNG in this special case assumes "selection of nothing" instead of "no selection", a bit confusing. If then one closes the mail, opens it again, and selects nothing, Print NG previews and prints the complete body as exspected.
2. I deleted dbg3 now since it nearly freezes my computer if I display the message pane and choose Print NG. It takes many minutes to be able to use the mouse again, to close the non-reacting Thunderbird, to close other programs and to shutdown the computer. This could be reproduced. What the hell is going on? I have no test environment, no sufficient knowledge to deal with such events and need a working computer. So I hesitate to participate in further testing and would rather stay with the stable version, sorry.

**Comment by cleidigh** [comment] 2022-03-16 23:55
@querixg 
I am sorry about your experience, I am surprised and have not seen that, but I understand your concern and I will try to reproduce.
I will let you know.
thanks for all your help so far.
Fyi dbg4 has only 1 line change !
@cleidigh

**Comment by cleidigh** [comment] 2022-03-20 19:31
@kiki-ja 
@querixg 
@reinerblock 
@RRoenn 
@tidebre67
All

I have fixed several edge cases as well as @kiki-ja and @querixg  Reports 
Because I have to use several tricks any help finding other issues appreciated.
@cleidigh 

[printing-tools-ng-2.1.0-dbg5-tb.Zip](https://github.com/cleidigh/printing-tools-ng/files/8312027/printing-tools-ng-2.1.0-dbg5-tb.Zip)

**Comment by querixg** [comment] 2022-03-21 19:39
Linux Mint 20.1 Kernel 5.4.0-104
Thunderbird 91.5.0
PTNG 2.1.0-dbg5

@cleidigh
I do admire your patience, and perseverence!

(After a bit of chaos on my computer experienced with dbg3 I now first created a seperate user account with standard settings of Mint and Thunderbird, but dbg5 works with my account and my settings as well.)

I tested normal print from mail toolbar (Print) and PTNG from menu bar (File > Print... (NG)), from mail toolbar (Print NG), from message header toolbar, from context menu (Print... (NG)), with Ctrl+P. I tested with message pane (View > Layout > Message Pane) on, with message pane off, with mail opened in a new window, with mail opened in a new tab, with mail only marked in the message list. I tested eml file opened in Thunderbird with File > Open > Saved message and opened with Thunderbird from file manager. Results:

- Print NG when message pane is beeing displayed o.k. now.
- No more inconsistency when switching between Print NG and Print.
- Multiple text selection o.k.
- Hide inline attachment list o.k.
- Print eml files o.k.
Great!

Minor issues:
- Print NG does not work if the message pane is not displayed and no mail is opened.
- Print NG is missing in the context menu of an eml file.
- If in the options of PTNG some text (which may be empty) is "added before headers" and a mail is printed (or its print previewed) several consecutive times, each time the mail is printed (or its print previewed) there is a new line added at the top of the body in the display of the mail (not in the preview or the printout). These lines disappear when the mail is opened/displayed anew.

**Comment by cleidigh** [comment] 2022-03-21 23:39
@querixg 
yes i am tenacious  ;-}
I like solving problems!

thanks for continuing testing 
i tweak these out.
I am happy the ms is working, had to do gymnastics for that
@cleidigh

**Comment by cleidigh** [comment] 2022-03-22 23:13
@querixg 
I am able to reproduce the first issue (noprint when the message pane is hidden)
I have fixed that.

I thought I saw the context issue then it was there, I will try to repeat.
I do not get newlines added when a string header is added.  Any other possible info on that?
@cleidigh

**Comment by querixg** [comment] 2022-03-23 07:19
I just repeated the test to get screenshots. Option: 
![Screenshot option](https://user-images.githubusercontent.com/87893156/159643665-f3dd7673-982f-4eb1-a152-bd4b43ca5695.png)
I opened a mail, chose Print NG, Cancel, Print NG, Cancel, Print NG, Cancel, Print NG, Cancel, Print NG, Cancel and step by step got five lines:
![Screenshot lines](https://user-images.githubusercontent.com/87893156/159644059-4993fe84-1c6a-4cae-ae77-8eaa8938201d.png)
The phenomenon does not depend on the specific mail opened.

**Comment by cleidigh** [comment] 2022-03-23 16:35
@querixg 
thanks 
So your screen shot shows actual lines like a border line?
I wonder if you can use the debug options 
initialsource and finaloutput 
then capture output 
that would show what the actual entity is being added 
I specifically remove headers after print l dealt with this earlier 
@cleidigh

**Comment by cleidigh** [comment] 2022-03-23 18:14
@querixg 
ok I got it!
I was able to get my Mint VM working and sure enough I reproduced it
No need for you to debug further, I will test.
@cleidigh

**Comment by cleidigh** [comment] 2022-03-23 18:43
@querixg 
unfortunately I cannot get mint to use a screen size i can see
its too small
im stuck...

**Comment by cleidigh** [comment] 2022-03-23 22:30
@querixg 
I spent the whole day getting a new Vm up.
I was using mint 19.1 and was able to reproduce the lines there.
The new vm is 20.3, there the problem is not seen.
This makes me think there is a tb mint issue. I really don't see how I would address that.  
any thoughts?
@cleidigh

**Comment by cleidigh** [comment] 2022-03-23 23:19
@querixg 
I think I found the issue, but needs some more digging.
this works on my 19.1
question, do you know how to increase the fonts in the debug console?

[printing-tools-ng-2.1.1-b1-tb.zip](https://github.com/cleidigh/printing-tools-ng/files/8337231/printing-tools-ng-2.1.1-b1-tb.zip)

**Comment by querixg** [comment] 2022-03-24 08:05
@cleidigh

2.1.1-b1 solves the "lines issue" (and the "message pane issue") on my computer, too!

> question, do you know how to increase the fonts in the debug console?

I think this could help:
Menu > Preferences > Accessibility > Desktop Zoom > Enable Zoom > ... (note, there is a lens mode, maybe enabling it is the better choice)

Moreover, Linux Mint allows text scaling by the following settings:
Menu > Preferences > Font Selection > Font Settings > Text scaling factor
Menu > Preferences > Font Selection > Font Selection > (choose font) > Size
And it is possible to double DPI:
Menu > Preferences > Display > Layout > User interface scale > Double (Hi-DPI)

But I still don't know where to find the debug console and how to use it.

**Comment by cleidigh** [comment] 2022-03-24 17:32
@querixg 
the hr ( horizontal rules) disappeared also right?
I forgot to tell you i fixed the other pane issue.
have to try the context menu one.
i will try the scaling, thanks!
btw after everything it had nothing to do with Linux 
it was no borders with the header name
I was a bit myopic/not thorough in my judgment, but now I have two vms ;-)
@cleidigh

**Comment by cleidigh** [comment] 2022-03-30 21:20
@querixg 
All
I think we can close this?
@cleidigh

**Comment by querixg** [comment] 2022-03-31 07:32
@cleidigh
I think so, too. Many thanks!!!

**Comment by cleidigh** [comment] 2022-03-31 18:12
@querixg 
Thanks !
@cleidigh

**Closed** 2022-03-31 18:12 UTC
Labels: enhancement
