### ISSUE TITLE
BUG | v.2.1.0 in Thunderbird 91.8.1 - print dialogue jammed to top edge of screen; cannot select Destination

### ISSUE THREAD

**Issue by boldcompany** [cleidigh/printing-tools-ng#117] opened 2022-04-21 18:42 UTC
Using PrintingTools NG v.2.1.0 in Thunderbird 91.8.1:
After selecting File > Print... (NG), the Print dialogue appears. It is jammed to the top edge of the screen. When clicking to select the print Destination, the dropdown does not work and options cannot be selected.

If PrintingTools NG is disabled, the native Thunderbird Print dialogue works as expected.

**Comment by cleidigh** [comment] 2022-04-21 20:21
@boldcompany 
Thanks for the post.
Can you give some more info including OS, locale and a screenshot
would be great.
This sounds very odd because with 91 there is a whole new print engine 
that PTNG invokes but does not alter as in the past.
I would be very interested to see this.
@cleidigh

**Comment by boldcompany** [comment] 2022-04-22 04:43
@cleidigh thanks for your quick reply.

OS=Windows 10 Pro 64-bit, latest patches, US English. Screenshot attached, which doesn't show much except that the dialogue is jammed to the top of the screen. The Destination selector cannot be clicked in this state.

![print-ng](https://user-images.githubusercontent.com/1261048/164604620-5e5a6061-895e-4476-989f-bc2eb0fa2a51.jpg)
n

**Comment by cleidigh** [comment] 2022-04-22 16:29
@boldcompany 
Thanks, I did learn something from the screen shot, you are using dark mode. No idea if it means anything.
So i do all the development on win10/64 and that's also the largest user base.  I have to say this is tricky as I have never seen anything effect the preview.

So because this is not reproducable by me are you able to work through some debugging?  Are you able to create a clean test  profile if we deem necessary?

Fist questions : 
- try light mode
- disable other extensions, can you enumerate?
- capture debug console output  (shift-control-j) select all,copy,post
- try changing some ptng options 
- can you change to landscape, any difference?

I will try dark mode, I don't use it, but I have other users that do
The new print engine came from Firefox so unfortunately there is not a lot of TB team experience in this.

Hopefully we can figure it out together.

One last test, you can try v2.1.1 beta which I am about to release.
Nothing that should effect this,but it's a test.

Here is the link: 

https://github.com/cleidigh/printing-tools-ng/blob/v2.1.1/xpi/printing-tools-ng-2.1.1-b12-tb.xpi

@cleidigh

**Comment by boldcompany** [comment] 2022-04-22 20:43
@cleidigh thanks again for your help on this.

A quick note on functionality as-is (with the existing setup, no changes): There are small areas in the Destination dropdown where clicking occurs successfully. They are the tiny areas at the top of the dropdown above any spaces in the destination text. For example, clicking above the space between the printer icon and the printer name, or above the spaces between words in the printer name, allows the dropdown selector to be used. So there's something strange about the targeting here.

Some notes per your questions:

- Changing dark/light mode (and trying various themes) did not seem to affect anything.
- Changing to landscape in Print dialogue does not make a difference.
- Even in a newly installed instance of Thunderbird, with Printing Tools NG as the only add-on, the Print dialogue is jammed to the top of the screen. (When PTNG is disabled, the Print dialogue appears as normal.)
- In Debug Console, the only notable entry I see is:
   cmd_printng startfalse [printingtoolsng-pengine.js:246:11]
   associated with each attempt to print.
- Changing PTNG options doesn't seem to affect anything. Do you have specific settings in mind?
- Disabling the add-on "QuickFolders" seems to resolve the issue of not being able to click the Destination selector. However, QuickFolders is a very important and useful add-on. If PTNG is disabled, the clicking issue does not occur with QuickFolders active and native print feature utilized.

Installation of v2.1.1 beta was attempted but Thunderbird reports:
"This add-on could not be installed because it appears to be corrupt."
Anything else needed besides the linked .xpi file above?

**Comment by cleidigh** [comment] 2022-04-22 20:56
@boldcompany 
ok, the plot thickens, I am more surprised that QF changes something, I may get Axel involved also.
When QF is disabled is the pv window still jammed up? Does every other button /UI element work?
Have you tried other printers  by setting the default printer in the options?
I'm spitballing as this just does not add up
@cleidigh

**Comment by cleidigh** [comment] 2022-04-22 20:59
Also how did you download and install the xpi? It's definitely not corrupt

**Comment by boldcompany** [comment] 2022-04-22 22:58
@cleidigh - answering your questions:

- When QuickFolders is disabled, the pv window is still jammed up. It is always jammed up whenever PTNG 2.1.0 is active, even in a fresh install of Thunderbird with no other add-ons.
- Every other button/UI element does work, just not the Destination dropdown selector.
- Trying other default printers does not affect this issue.
- There must have been a network glitch (or something) earlier, as the beta .xpi download/install was attempted multiple times from multiple browsers but always resulted in the "corrupt" error. Trying the download/install again now, it successfully installed.

The good news:
With the beta PTNG 2.1.1-b12, neither of the issues (top-jam, destination-unclickable) remains. 
Version 2.1.1 appears to resolve the issues.

**Comment by cleidigh** [comment] 2022-04-22 23:30
@boldcompany 
That's excellent!
I had to make a lot of changes for multiple selection and somehow somewhere there must have been an interaction with the preview window.
The next release will be ready for the review Q in a few days.
Shall we close this?
Thanks for working through this.
@cleidigh

**Closed** 2022-04-23 00:08 UTC
